ioos/conda-recipes

- airsea/meta.yaml
- geolinks/meta.yaml
- octant/meta.yaml
- pycsw/meta.yaml
- rasterio/meta.yaml
- thredds_crawler/meta.yaml
- udunitspy/meta.yaml
Using https we do not need a password nor a ssh key to build packages.  This is required to build packages using the new binstar build VM.
> Changed from ssh to https.

- owslib/bld.bat
@rsignell-usgs we forgot the `bld.bat`.  With this PW we can build any OWSLib version and forget about OWSLib issues here https://github.com/ocefpaf/utilities/issues/1.
> Fixed windows build.

- pygridgen/meta.yaml
`new-paths` branch is no longer there.  I am using `master`, but we should confirm with @phobson if that is the right branch to build pygridgen.
> Using master branch to build pygridgen.

- rasterio/meta.yaml
- rdflib/build.sh
- rdflib/meta.yaml
- sparqlwrapper/meta.yaml
This is a workaround to fix #17.  We must build `rdflib` and then `sparqlwrapper`.  When installing we have to install `sparqlwrapper` and get `rdflib` automatically.  It will not work if someone install `rdflib` only!
> Workaround rdflib-sparqlwrapper circ dependency

- rasterio/meta.yaml
I found that the cython error we got were due to the GitHub tagged version.  I believe there are some left over cythonized sourced there.  Once I moved to a clean source (PyPI) things worked out smoothly for all rasterio version.
Here I also updated it to the latest version (0.18).
> Updated rasterio to 0.18 and use PyPI source.

- README.md
The AppVeyor link is broken because the account does not exist yet.  Lets wait until we create the account to merge this one.
> Added badges (and break lines).

- README.md
We must change `project/ocefpaf` to `project/ioos` in the future...
> Fixed AppVeyor and Binstar URLs.

- rdflib/bld.bat
- rdflib/build.sh
- rdflib/meta.yaml
Using `pip` instead of `wget` the circular dependency work around it OS agnostic (and more robust).
> Fix `rdflib` windows build.

- psycopg2/bld.bat
- psycopg2/build.sh
- psycopg2/meta.yaml
@rsignell-usgs This will download a binary from PyPI using pip and create a conda package from it.  I remember reading about this in the conda e-mail list somewhere...
The psycopg2 package works only on win64 and linux (no win32).  With that we can build `pycsw` for [win64](https://binstar.org/ioos/pycsw).  However, both packages are not tested.
> Adding psycopg2 (Cheating: using pip).

- .travis.yml
- iris/meta.yaml
In this PR:
- enable grib
- enable pp
- increment build
- added explicit dependency on `libnetcdf >=4.3`
The reason behind the last item is that, somehow, conda downloaded the non-dap enable
`libnetcdf:          4.2.1.1-0                    defaults`
To fix that I had to manually update `libnetcdf`.  In theory, by forcing the dap enabled version, we are OK by just installing iris.
PS: This gist show a small requirements file and what gets installed by it using conda and only the ioos channel.
https://gist.github.com/ocefpaf/e594e228bc8129303006
> Some recipe improvements

- compliance-checker/bld.bat
- mysql-python/bld.bat
- octant/bld.bat
- pytools/bld.bat
- rasterio/bld.bat
- rtree/bld.bat
- udunitspy/bld.bat
Removed the following windows build to allow AppVeyor to complete.
rtree/bld.bat
octant/bld.bat
pytools/bld.bat
rasterio/bld.bat
udunitspy/bld.bat
mysql-python/bld.bat
compliance-checker/bld.bat
I will revisit every package again at a later time to fix their windows build individually.
> First step to fix windows builds.

- psycopg2/bld.bat
- psycopg2/meta.yaml
This PR adds an IF/ELSE clause in the `bld.bat` to install the proper `psycopg2` binary for each ARCH.  Because the binary available for win32 is 2.5.2 I downgraded the package to that version.
(`pycsw` is the only package that uses `psycopg2`.)
This PR closes #81.
> Fix win32 build.

- iris/bld.bat
- iris/meta.yaml
This PR adds iris build for windows (`bld.bat`) and updates iris to the latest release.
The update is because version 1.7.2 cannot by built on windows.  However, we must add `iris==1.7.2_DEV_9e1fd13` to our requirements file on Linux to avoid installing the latest version until this bug is fixed:
https://github.com/SciTools/iris/pull/1502
and live with the bug on windows...
> Added iris for windows.

- obvious-ci/bld.bat
- obvious-ci/build.sh
- obvious-ci/meta.yaml
`obvious-ci` as a first step to write the "How to run `obvci_conda_build_dir.py` on https://github.com/ioos/conda-recipes."
@rsignell-usgs Can you review and merge?
> Added obvious-ci

- libspatialindex/build.sh
- libspatialindex/meta.yaml
This is so that autoconf will have already been run -- so you can build with a simple:
./configure && make && make install
Note that OS-X doesn't have autotools installed by default, so this makes it a lot easier to build on OS-X
And it seems the "official" source tarball is probably the way to go anyway.
> re-wrote libspatialindex to download source tarball, rather than pull from gitHub

- utilities/meta.yaml
@rsignell-usgs this release adds a workaround for iris slicing bug on Windows 64.
> Updated to latest release.

- appveyor.yml
- bootstrap-obvious-ci-and-miniconda.py
AppVeyor is failing to install wget using chocolatey.  I decided to add the bootstratp script directly in our repository.  We are using Obvious-CI v0.1.0 from:
`https://raw.githubusercontent.com/pelson/Obvious-CI/v0.1.0/bootstrap-obvious-ci-and-miniconda.py`
> Fix wget download on AppVeyor

- geos/build.sh
- shapely/meta.yaml
@rsignell-usgs This is safe to merge and will not affect the binaries on binstar.  It only makes the package more friendly to old Linux distros.
(If one day we want to use these package on Wakari, we will need this.)
> Build on RHEL6  (conda-recipes-scitools #54).

- .travis.yml
- Installs gfortran (via apt-get) only for Linux.
- Removed sudo calls (not need on travis-ci)
> Install gfortran on Linux only.

- 00_env_requirements/ioos/ioos_req.txt
@rsignell-usgs this should work on MacOS too.  In the it was a `libnetcdf` update (4.2.1.1 -> 4.3.2-1).  By removing the pinned down built from our req file (4.2.1.1-1) everything works.
PS: We had to pin` libnetcdf` to 4.2.1.1-1 because the build=0 was not Dap enabled and somehow conda was picking that one up.  Version 4.3.2 is OK though.
> Fixes #118.

- compliance-checker/meta.yaml
Bump compliance checker to git_tag 1.0.2
- Station Variable Support
- Bug Fixes
- Initial Conda help
- Exit Code
- Opens room for future CF conventions
- GliderDAC Compliance Checker
> Bump compliance checker.

- 00_env_requirements/ioos/ioos_req.txt
- biggus/meta.yaml
- iris/meta.yaml
Using `iris` and `biggus` from @rhattersley branch.  This is a workaround until https://github.com/SciTools/iris/pull/1560 get merged.
> Using lazy_dtype branch (again).

- biggus/meta.yaml
Release notes: https://github.com/SciTools/biggus/releases/tag/v0.10.0
> YABU (Yet Another Biggus Update ;-)

- .travis.yml
- nco-bindings/build.sh
- nco-bindings/meta.yaml
- nco/build.sh
- nco/meta.yaml
@rsignell-usgs this will probably fail or it will produce a defective/incomplete nco.  That is because the default channel does not provide antlr nor [gsl](https://github.com/conda/conda-recipes/tree/master/gsl).
I just want to see the failure to have something to work with.
> Adding nco.

- folium/meta.yaml
Latest folium release:
Popups allow unicode.  (apatil)
Support for https protocol.  (apatil)
Custom popup width.  (ocefpaf)
Support multiPolyLine.  (scari)
Added max and min zoom keywords.  (Paradoxeuh)
Bug Fixes
Remove margins from leaflet-tiles (Fixes #64).  (lennart0901)
Template not found on Windows OSes (Fixes #50).  (Paradoxeuh)
WMS layer on python 3.  (ocefpaf)
> Updated folium to 0.1.4

- udunits2/meta.yaml
2.2.19
- Added `tsearch.c` and `tsearch.h` to the distribution to support building on Windows.
2.2.18
Library (udunits2(3)):
- Eliminated the use of <unistd.h> on Windows.
- Improved support for static builds.
Units Database:
- Corrected the definition of "dram" and added "fluid_dram".
- Changed the definition of "molecule" to "1/avogadro_constant".
- Added comments and human-readable definitions.
- Improved support for static builds.
Program (udunits2(1)):
- Removed latent bug on Windows in determining the name of the program.
Misc:
- Removed lint discovered by Coverity.
> Updated to 2.2.19

- appdirs/bld.bat
- appdirs/build.sh
- appdirs/meta.yaml
- [PR #42] AppAuthor is now optional on Windows
- [issue 41] Support Jython on Windows, Mac, and Unix-like platforms. Windows support requires JNA.
- [PR #44] Fix incorrect behaviour of the site_config_dir method
- [Unix, issue 16] Conform to XDG standard, instead of breaking it for everybody
- [Unix] Removes gratuitous case mangling of the case, since *nix-es are usually case sensitive, so mangling is not wise
- [Unix] Fixes the uterly wrong behaviour in site_data_dir, return result based on XDG_DATA_DIRS and make room for respecting the standard which specifies XDG_DATA_DIRS is a multiple-value variable
- [Issue 6] Add *_config_dir which are distinct on nix-es, according to XDG specs; on Windows and Mac return the corresponding *_data_dir
> Updated appdirs.

- obvious-ci/meta.yaml
We are using the master branch (development version 0.3.x), so I bumped the build number to get the latest checkout.  We need this to get the  this fix: https://github.com/pelson/Obvious-CI/pull/4
> Bumped the build number.

- rasterio/build.sh
- rasterio/meta.yaml
- snuggs/bld.bat
- snuggs/build.sh
- snuggs/meta.yaml
0.19.1 (2015-03-30)
- Add missing blockxsize, blockysize, tiled keywords (#301).
0.19.0 (2015-03-25)
- New rio-calc command (#175).
- Added a file band shortcut to fillnodata() (#271).
- Added fillnodata() to rio-calc functions (#277).
- New approach to masking arrays on read that conforms more closely to GDAL's
RFC 15 (#282, #284, #285).
- New read_masks() method (#284).
- Deprecation of read_mask() and read_band (#284).
- New affine transform factory functions from_origin(), from_bounds() (#287).
- Improve correctness of indexing and rio-merge logic (#288, #290).
> Updated rasterio.

- click/bld.bat
- click/build.sh
- click/meta.yaml
Version 4.0
-----------
(codename "zoom zoom", released on March 31st 2015)
- Added `color` parameters to lots of interfaces that directly or indirectly
call into echoing.  This previously was always autodetection (with the
exception of the `echo_via_pager` function).  Now you can forcefully
enable or disable it, overriding the auto detection of Click.
- Added an `UNPROCESSED` type which does not perform any type changes which
simplifies text handling on 2.x / 3.x in some special advanced usecases.
- Added `NoSuchOption` and `BadOptionUsage` exceptions for more generic
handling of errors.
- Added support for handling of unprocessed options which can be useful in
situations where arguments are forwarded to underlying tools.
- Added `max_content_width` parameter to the context which can be …
> Updated click

- coveralls/bld.bat
- coveralls/build.sh
- coveralls/meta.yaml
1.0a2 (2015-02-19)
* Fix latest alpha coverage.py support
* Remove erroneous warning message when writing output to a file
1.0a1 (2015-02-19)
* **Backwards incompatible**: make pyyaml optional. If you're using .coveralls.yml, make sure to install coveralls[yaml]
* Coverage 4 alpha support
* Allow debug and output options to work without repo_token
* Fix merge command for python 3.X
> Updated coveralls

- python-dateutil/bld.bat
- python-dateutil/build.sh
- python-dateutil/meta.yaml
Updated zoneinfo to 2015b.
- Fixed issue with parsing of tzstr on Python 2.7.x; tzstr will now be decoded if not a unicode type. gh #51 (lp:1331576), gh pr #55.
- Fix a parser issue where AM and PM tokens were showing up in fuzzy date stamps, triggering inappropriate errors. gh #56 (lp: 1428895), gh pr #63.
- Missing function "setcachsize" removed from zoneinfo all list by @ryanss, fixing an issue with wildcard imports of dateutil.zoneinfo. (gh pr #66).
- (PyPi only) Fix an issue with source distributions not including the test suite.
> Updated dateutil.

- flopy/bld.bat
- flopy/build.sh
- flopy/meta.yaml
(Fix #167 )
- FloPy3 now supports some simple mapping and cross-section capabilities through the flopy.plot submodule. See the notebook flopy3_MapExample.
- Full support for all Output Control (OC) options including DDREFERENCE, SAVE IBOUND, and layer lists. All Output Control Input is specified using words. Output Control Input using numeric codes is still available in the ModflowOc88 class. The ModflowOc88 class is currently deprecated and no longer actively maintained.
- Added support for standard MULT package FUNCTION and EXPRESSION functionality are supported. MODFLOW parameters are not supported in write() methods.
- FloPy3 is significantly different from FloPy2 (previously hosted on googlecode). The main changes are:
- FloPy3 is fully zero-based. This means that layers, rows and …
> Updated flopy

- isodate/bld.bat
- isodate/build.sh
- isodate/meta.yaml
0.5.1 (2014-11-07)
- fixed pickling of Duration objects
- raise ISO8601Error when there is no 'T' separator in datetime strings (Adrian Coveney)
0.5.0 (2014-02-23)
- ISO8601Error are subclasses of ValueError now (Michael Hrivnak)
- improve compatibility across various python variants and versions
- raise exceptions when using fractional years and months in date
maths with durations
- renamed method todatetime on Duraction objects to totimedelta
> Updated isodate

- rdflib/bld.bat
- rdflib/build.sh
- rdflib/meta.yaml
2015/02/19 RELEASE 4.2.0
========================
This is a new minor version of RDFLib including a handful of new features:
* Supporting N-Triples 1.1 syntax using UTF-8 encoding
[#447](https://github.com/RDFLib/rdflib/pull/447),
[#449](https://github.com/RDFLib/rdflib/pull/449),
[#400](https://github.com/RDFLib/rdflib/issues/400)
* Graph comparison now really works using RGDA1 (RDF Graph Digest Algorithm 1)
[#441](https://github.com/RDFLib/rdflib/pull/441)
[#385](https://github.com/RDFLib/rdflib/issues/385)
* More graceful degradation than simple crashing for unicode chars > 0xFFFF on
narrow python builds. Parsing such characters will now work, but issue a
UnicodeWarning. If you run `python -W all` you will already see a warning on
`import rdflib` will show a warning (ImportWarning). …
> Updated rdflib.

- djangorestframework/bld.bat
- djangorestframework/build.sh
- djangorestframework/meta.yaml
- sci-wms-deps/meta.yaml
- setproctitle/bld.bat
- setproctitle/build.sh
- setproctitle/meta.yaml
This PR closes #173.
@rsignell-usgs and @kwilcox I would like to:
What do you think?  Worth pursuing? This script would be something like `sci-wms [new|deploy|help|serve]` format.
> Sci-wms repo and recipe update.

- oct2py/bld.bat
- oct2py/build.sh
- oct2py/meta.yaml
This package relies on the system installed octave.  Creating a conda package for octave is a little bit tricky.
> Added oct2py

- rtree/find_libray.patch
- rtree/meta.yaml
This patch hard-codes the conda lib patch to ensure the module will find the conda version of the c-lib and not a system c-lib.  The same must be done for OSX and Windows.
Closes #184
> Added Linux find_library patch

- cartopy/meta.yaml
@rsignell-usgs If a user install the latest proj4 with the current cartopy s/he may get an error like
```python
ImportError: libproj.so.0: cannot open shared object file: No such file or directory
``` 
Re-building it against latest `proj4` should solve the issue.
> Re-build cartopy with proj4-4.9.1

- ulmo/bld.bat
- ulmo/build.sh
- ulmo/meta.yaml
**0.7.6 (released 2015-04-27)**
- fixed ncdc.gsod services to use new station list over depreciated list (thanks Victor)
- added USGS National Elevation Dataset (NED) raster service
- added USGS Earth Resources Observation Systems (EROS) raster services
- allow passthrough of extra kwargs for USGS NWIS services
> Updated ulmo

- cartopy/meta.yaml
PIL is deprecated and its use is holding back some updates when trying: `conda update --all`.
> Using pillow instead of PIL

- .travis.yml
- cartopy/meta.yaml
- geos/meta.yaml
- mplleaflet/bld.bat
- mplleaflet/build.sh
- mplleaflet/meta.yaml
- shapely/meta.yaml
Using a release instead of `master` for mplleaflet.
> Changing mplleaflet master -> PyPI

- .travis.yml
- cartopy/meta.yaml
- geos/meta.yaml
- proj4/meta.yaml
- rasterio/meta.yaml
- shapely/meta.yaml
Changes
=======
0.21.0 (2015-04-22)
- New rio-mask command (#323).
- Masking bug fix for rio-shapes (#335).
- Addition of single valued nodata property to be used instead of nodatavals
(#329).
0.20.0 (2015-04-08)
- Switch read() default to masked=False (#300, #317).
- Fix documentation of masking throughout module (#305).
- Remove option for in place nodata filling (#309).
- Enhancements for valid data footprint extraction in rio-shapes (#316, #318).
> Updates rasterio to v0.21.0

- mo_pack/meta.yaml
Pointing `mo_pack` to latest release instead of `master`.
> Updated to latest release

- .travis.yml
- pyaxiom/meta.yaml
@kwilcox This complements PR #229.
Just some notes on conda packaging:
In conda we reset the build number every new version.  And we bump the build number when changing the package in the same version.  Suppose we get `nco` going for Mac we would create pyaxiom-0.0.9-**1**.
Also, the conda syntax to apply (or do not apply) specific changes to a certain platform are listed here:
http://conda.pydata.org/docs/build.html#preprocessing-selectors
Thanks for the PR!
> Fixed pyaxiom build for Windows and Mac

- geos/build.sh
Just to make 32 and 64 builds a little bit easier.  I am not bumping the build number on purpose.  The 64 `geos` would not change and the 32 is already in the channel, which uses this PR and the docker image.
> Use 32 or 64 flags.

- appveyor.yml
- bootstrap-obvious-ci-and-miniconda.py
- iris/meta.yaml
- The PP loader now carefully handles floating point errors in date time conversions to hours.
- The handling fill values for lazy data loaded from NetCDF files is altered, such that the _FillValue set in the file is preserved through lazy operations.
- The risk that cube intersections could return incorrect results due to floating point tolerances is reduced.
- The new GRIB2 loading code is altered to enable the loading of various data representation templates; the data value unpacking is handled by the GRIB API.
- Saving cube collections to NetCDF, where multiple similar aux-factories exist within the cubes, is now carefully handled such that extra file variables are created where required in some cases.
> iris 1.8.1

- tardis/bld.bat
- tardis/build.sh
- tardis/meta.yaml
- utilities/meta.yaml
I factored `iris_utils` out of `utilities` and added it as a dependency.  Nothing changes if someone install installs `utilities`, but now people can use `iris_utils` without installing unnecessary modules.
> Adding tardis and updated utilities.

- cdo/build.sh
- cdo/meta.yaml
- select: added parameter date, startdate, enddate
- expr: added support for operator ?:,&&,||
- option --reduce_dim: reduce dimension (Timstat, Fldstat)
- after: ECHAM standard post processor
- aexpr: Evaluate expressions and append results
- aexprf: Evaluate expression script and append results
- selzaxisname: Select z-axes by name
- genlevelbounds: Generate level bounds
- ydrunpctl: does not work in combination with ydrunmin/ydrunmax
- Ensstat: added support for different missing values
- seltimestep: abort if none of the selected timesteps are found
> Adding cdo.

- cyordereddict/bld.bat
- cyordereddict/build.sh
- cyordereddict/meta.yaml
- h5netcdf/bld.bat
- h5netcdf/build.sh
- h5netcdf/meta.yaml
- xray/bld.bat
- xray/build.sh
- xray/meta.yaml
This PR adds:
- `cyordereddict`
- `h5netcdf`
and updates `xray` to `0.5.0` using `h5netcdf`, `cyordereddict` and `dask`.
> Update xray and adds some optional dependencies

- nco/meta.yaml
* This is the first NCO release that supports regridding datasets, currently
limited to global datasets. These features build on infrastructure
pioneered by Phil Jones (SCRIP), and the multi-agency Earth System
Modeling Framework (ESMF). Other noteworthy improvements include
capturing history from appended files, and that ncdismember uploads to
the NERC CF-checker upon request.
> Updated nco to 4.5.0

- ecmwf_grib/meta.yaml
- jasper/meta.yaml
Newer RHEL jasper had a lower build number than an older version.  That was causing all sort of issues with other packages that depended on jasper.
> Bug in jasper release

- simplekml/bld.bat
- simplekml/meta.yaml
- Fixed “global” styles repeating in each container.
- Fixed ampersand (&) not escaping correctly in urls.
- Fixed problem where files added via simplekml.Kml.addfile() were forgotten.
- Moved the method simplekml.Kml.addfile() from being available from all classes to being available only via simplekml.Kml
> Updated simplekml to 1.2.8

- .travis.yml
- nco/build.sh
- nco/meta.yaml
- nco/nodocs.patch
- pyaxiom/meta.yaml
Mac OS X build hints (from http://nco.sourceforge.net/build_hints.shtml):
Mac OS X users report success building NCO without patches so long as they
- (1) Install the latest version of bison
- (2) Disable shared libraries and
- (3) Disable extended regular expressions.
This is done with
```bash
./configure --disable-regex --disable-shared
```
Building NCO with shared libraries on Mac OS X on may be possible.  To try, first re-build and re-install
the netCDF library using `CFLAGS=-fno-common`.  Apparently netCDF, unlike most codes, does not set
this automatically.  Then build NCO normally.
Mac OS X ships with a broken version of the POSIX `cut` utility which causes many NCO regression
tests to appear to fail.  In fact the NCO commands succeed, but the `cut` output fails.  The workaround is …
> Testing NCO on OSX

- simplejson/bld.bat
- simplejson/build.sh
- simplejson/meta.yaml
imports `simplejson._speedups` to assure that the Cython module got built.
> Speedups import test.

- pycsw/meta.yaml
This version of pycsw (1.10.2) patches a important security issue that comes from libxml2 versions before 2.9.2: 
"parser.c in libxml2 before 2.9.2 does not properly prevent entity expansion even when entity substitution has been disabled, which allows context-dependent attackers to cause a denial of service (CPU consumption) via a crafted XML document containing a large number of nested entity references, a variant of the "billion laughs" attack."
> pycsw security issue

- cartopy/bld.bat
- cartopy/build.sh
- cartopy/meta.yaml
* Andrea Smith fixed the cartopy CRS class such that 3d transforms such as :class:`cartopy.crs.Geocentric`
now correctly apply deg2rad and rad2deg.
* Peter Killick fixed the cartopy.crs.Mercator projection for non-zero central longitudes.
* Conversion between matplotlib :class:`matplotlib.path.Path` and
:class:`shapely.geometry.Geometry <Shapely geometry>` using
:func:`cartopy.mpl.patch.path_to_geos` and :func:`cartopy.mpl.patch.geos_to_path` now
handles degenerate point paths.
* Update of tools/feature_download.py to allow mass download of feature data rather than
on-demand downloading.
> Update cartopy to v0.13.0

- nco/meta.yaml
This release improves regridding features, ncra weighting, and
ncatted flexibility, and contains a raft of minor fixes and tunings.
Notably, most implementation-specific dimension/variable names
involved in regridding can be specified at the command line, and
the regridder understands mapfiles generated by TempestRemap.
ncra can now weight records by a 1-D record variable in the file.
And ncatted supports regular expressions in both the variable name
AND the attribute name (simultaneously, too).
> Update nco to 4.5.1

- protobuf/bld.bat
- protobuf/build.sh
- protobuf/meta.yaml
- siphon/bld.bat
- siphon/build.sh
- siphon/meta.yaml
- Siphon - A collection of Python utilities for retrieving data from Unidata data technologies.
An example from a mailing list:
```python
from siphon.catalog import TDSCatalog
latest_hrrr = TDSCatalog('
http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/surface/latest.xml
')
hrrr_ds = list(latest_hrrr.datasets.values())[0]
from siphon.ncss import NCSS
ncss = NCSS(hrrr_ds.access_urls['NetcdfSubset'])
query = ncss.query()
query.all_times().accept('netcdf4').variables('Temperature_surface')
query.lonlat_box(45, 30, -100, -90)
data = ncss.get_data_raw(query)
with open('test.nc', 'wb') as outf:
outf.write(data)
```
> Added siphon

- yaml2ncml/meta.yaml
upgrading to 0.2.0
- adds standard_name for time coordinate variable
- specifies project metadata correctly
> update yaml2ncml to 0.2.0

- obvious-ci/meta.yaml
`binstar` was renamed to `conda-server`
> Updated Obvious-CI dependencies

- sci-wms/meta.yaml
This looks pretty complete, though there are a few things that aren't needed anymore.
* South
* Shapely
* Basemap
You don't need the debug-toolbar unless you're running a development machine, but that's not that critical. A user with server access could disable it at his/her discretion by modifying settings.
I've also taken this opportunity to make a pysgrid release.
> Unneded deps on sciwms dependencies

- pyshp/bld.bat
- pyshp/build.sh
- pyshp/meta.yaml
- 1.2.3: Bugfix for Python3 with Reader.iterShapeRecords()
- 1.2.2: Adds Reader.iterShapeRecords() for reading large shapefiles
> Update pyshp to 1.2.3

- seawater/bld.bat
- seawater/build.sh
- seawater/meta.yaml
- Unified code base for python 2 and 3, we no longer use 2to3 to convert.
> Updated seawater to 3.3.3

- geojson/meta.yaml
1.2.2 (2015-07-13)
- Fix tests by including test file into build
- https://github.com/frewsxcv/python-geojson/issues/61
- Build universal wheels
- https://packaging.python.org/en/latest/distributing.html#universal-wheels
1.2.1 (2015-06-25)
- Encode long types correctly with Python 2.x
- https://github.com/frewsxcv/python-geojson/pull/57
1.2.0 (2015-06-19)
- Utility function to validate GeoJSON objects
- https://github.com/frewsxcv/python-geojson/pull/56
> Updated geojson to 1.2.2

- pyhum/meta.yaml
- 1) map and map_texture:
implemented various ways to stop the programs crashing if low on memory, due to a grid size creating gridded data sets too large for system memory. If the system is about to crash, resolutions are doubled and functions rethrown. It will continue to do this until a gridded data set has been created.
Gridding routines now rely on the fast pyresample module. 3 types of nearest neighbour interpolation are now supported: 1) ordinary; 2) inverse distance weighted; and 3) gaussian weighted. Use the 'mode' flag in 'map' and 'map_texture'
- 2) Point cloud outputs from the “map” module now contain georeferenced depths, ranges and headings as well as sidescan pixel intensities. This is useful in its own right, for subsequent analysis, but mostly in anticipation of a …
> Updated PyHum to 1.3.2

- shapely/bld.bat
- shapely/meta.yaml
- shapely/stdint.h
- utilities/meta.yaml
Version 0.2.5
* Added more CF-names to the velocity list.
* Added ioos module with system-test functions.
* Replaced `get_coops_longName()` with `get_coops_metadata()`
* Added Root Mean Squared Error`rmse()` and all of sklearn.metrics
(`mean_absolute_error`, `mean_squared_error`, `median_absolute_error`,
`r2_score`, `explained_variance_score`).
> Updated utilities to 0.2.5

- shapely/bld.bat
- shapely/meta.yaml
- shapely/stdint.h
Note to future self:
Visual Studio is missing `stdint.h`.
```
c:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Miniconda\envs\_build\Library\include -IC:\Miniconda\envs\_build\include -IC:\Miniconda\envs\_build\PC /Tcshapely/speedups/_speedups.c /Fobuild\temp.win32-2.7\Release\shapely/speedups/_speedups.obj
_speedups.c
shapely/speedups/_speedups.c(248) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
command 'c:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2
```
That can be solved by downloading it from [here](http://msinttypes.googlecode.com/svn/trunk/stdint.h) and adding the the `%RECIPE_DIR%` in the `INCLUDE`.  Not sure if this is the best way to go, but it …
> Update Shapely to 1.5.9

- ulmo/bld.bat
- ulmo/meta.yaml
**0.7.8 (released 2015-07-02)**
- no changes, had to bump version number because of a corrupt file uploaded to pypi.
**0.7.7 (released 2015-07-02)**
- dropped python 2.6 support
- fixed bug in extracting raster file from zip file on windows
- fixes for cdec service
- fix url_params kwarg typo for nwis service
> Updated ulmo to 0.7.8

- siphon/meta.yaml
- Handle radarserver metadata 27 46 37
- Simplify following CatalogRef urls 35
- Warn and try xml link in TDSCatalog if passed HTML link 32
- Add info for conda development environment 41
- Be less pedantic in validating catalogs 28
> Updated siphon to 0.3.1

- simplejson/meta.yaml
* New iterable_as_array encoder option to perform lazy serialization of
any iterable objects, without having to convert to tuple or list.
> Updated simplejson to 3.8.0

- tardis/meta.yaml
Version 0.1.1
* Fixed a bug in `save_timeseries ` to cast all netCDF4 variables in the
expected dtype.
> Updated tardis to 0.1.1

- sci-wms/bld.bat
- sci-wms/build.sh
According to the conda mailing list we do not need `build.sh` and `bld.bat` for metapackages.
> Better metapackages

- folium/meta.yaml
> Using PyPI release instead of git hash

- django-debug-toolbar/meta.yaml
- django-extensions/meta.yaml
@kwilcox this should help you with https://github.com/sci-wms/sci-wms/pull/68
In theory we do not need to do this.  Conda should use the proper version if everything were in one `requirements.txt` file and only one line with `django >=1.7,<1.8` there should do the trick.  Since we only have these packages for `sci-wms` I do not see the harm in enforcing the version here too.  Let me know if there are more roadblocks like this.
> Pin Django version

- xray/meta.yaml
v0.6.0 (21 August 2015)
-----------------------
This release includes numerous bug fixes and enhancements. Highlights
include the introduction of a plotting module and the new Dataset and DataArray
methods :py:meth:`~xray.Dataset.isel_points`, :py:meth:`~xray.Dataset.sel_points`,
:py:meth:`~xray.Dataset.where` and :py:meth:`~xray.Dataset.diff`. There are no
breaking changes from v0.5.2.
> Update xray to 0.6.0

- octant/bld.bat
Sadly I could not get `mingwpy` to work on AppVeyor Win64.
> Remove octant for Win64

- libmo_unpack/build.sh
- libmo_unpack/meta.yaml
Easier than installing a newer autoreconf on Centos.
(See https://github.com/SciTools/conda-recipes-scitools/pull/101/files.)
> libmo_unpack patch

- cf_units/meta.yaml
- compliance-checker/meta.yaml
- iris/meta.yaml
- octant/meta.yaml
- optcomplete/meta.yaml
- paegan-transport/meta.yaml
- petulant-bear/meta.yaml
- pycsw/meta.yaml
- pygdp/meta.yaml
- pyhum/meta.yaml
- suds/meta.yaml
- tardis/meta.yaml
- ulmo/meta.yaml
- unit_conversion/meta.yaml
- utilities/meta.yaml
- wicken/meta.yaml
Using `<3` in both the `build` and `run` produced packages without the `py` version string!  In this PR we test specifying a more restrictive condition on the `build` only.
http://anaconda.org/IOOS/iris/1.8.1/download/linux-64/iris-1.8.1-np_1.tar.bz2
> Bake python string

- owslib/meta.yaml
Updates the requirements  for OWSLib with `lxml` and `pyproj`.
@rsignell-usgs ths should solve https://github.com/USGS-CIDA/pyGDP/issues/120#issuecomment-137390878
> Added extra reqs

- geolinks/meta.yaml
Python 3K support, slight API changes
```python
>>> from geolinks import sniff_link
>>> sniff_link('http://host/wms?service=WMS')
'OGC:WMS'
>>> sniff_link('http://host/wms?service=WPS')
'OGC:WPS'
>>> sniff_link('http://host/wms?service=CSW')
'OGC:CSW'
>>> sniff_link('http://host/data/roads.kmz')
'OGC:KML'
>>> sniff_link('http://host/data/roads.kml')
'OGC:KML'
```
> Updated geolinks to 0.2.0

- nco/build.sh
- nco/meta.yaml
- NEW FEATURES
- A. All operators can now add user-specified global attributes to
output files using the --glb switch. The switch takes mandatory
arguments --glb att_nm=att_val where att_nm is the desired name of
the global attriute to add, and att_val is its value.
Currently only text attributes are supported (recorded as type
NC_CHAR, and regular expressions are not allowed (unlike ncatted).
Multiple invocations simplify the annotation of output file at
creation (or modification) time, and incur no performance penalty.
Should users emit a loud hue and cry, we will consider ading the
the functionality of ncatted to the front-end of all operators,
i.e., accepting valid arguments to modify attributes of any type
and to apply regular expressions.
ncra --glb machine=${HOSTNAME} --glb …
> Update nco to 4.5.2

- suds-jurko/bld.bat
- suds-jurko/build.sh
- suds-jurko/meta.yaml
Latest update on `suds-jurko` was 2015-07-27, so that is better than suds... And we get Python3 too.
> Added suds-jurko

- biggus/bld.bat
- biggus/build.sh
- biggus/meta.yaml
- A fix for the `__getitem__` for `LinearMosaic` that corrects array slicing output (147).
- Biggus' `__div__` method properly accounts for the dtype of arguments passed to it (149).
- Added support for Python 3.5 (150).
> Update biggus to 0.12.0

- gridgen/build.sh
- gridgen/meta.yaml
This PR fixes
- source for the code
- version number
- license and some more metadata
NB: The `triangle.[c,h]` license is non-free for commercial use! :ghost:
> Updated gridgen to 1.50.0

- gridutils/build.sh
- gridutils/meta.yaml
This PR fixes code source, code license, updated version, and add some extra metadata.
Changelog
--------------
- v. 0.54, 5 May 2015
- Introduced gu_setquitfn() to set the quit function externally;  the previous (internal) version is used as default.
- v. 0.53, 3 Mar 2015
- Corrected the header guard in gridnodes.h
- v. 0.52, 4 Jul 2013
- Added a new constructor gridnodes_create2()
- Using a saved errno in strerror() now
> Updated gridutils to 1.0

- pyhum/meta.yaml
- 1) Fixed small bug in e1e2 module that was using smoothed easting/northing coordinates rather than actual coordinates
- 2) in map module, if mode =3 (nearest neighbour with gaussina smoothing), the sigma on the gaussian function has been changed from 1 to 0.1, due to sigma = 1 oversmoothing. Will implement this as a user input variable in a future release
- 3) the 'correct' module now has a new flag, 'correct_withwater'. If correct_withwater=0 [default], the usual/old behaviour is observed. If correct_withwater=1, radiometric corrections are carried out on scans without water column removed, and a new set of files (*__data_star_lw.dat and *_data_port_lw.dat) are produced
> Updated pyhum to 1.3.3

- shapely/geos_c.win.patch
- shapely/meta.yaml
Changes
=======
1.5.12 (2015-08-27)
- Remove configuration of root logger from libgeos.py (312).
- Skip test_fallbacks on Windows (308).
- Call setlocale(locale.LC_ALL, "") instead of resetlocale() on Windows when
tearing down the locale test (308).
- Fix for Sphinx warnings (309).
- Addition of .cache, .idea, .pyd, .pdb to .gitignore (310).
> Updated Shapely to 1.5.12

- blinker/bld.bat
- blinker/build.sh
- blinker/meta.yaml
- feedgenerator/bld.bat
- feedgenerator/build.sh
- feedgenerator/meta.yaml
- ghp-import/bld.bat
- ghp-import/build.sh
- ghp-import/meta.yaml
- pelican/bld.bat
- pelican/build.sh
- pelican/meta.yaml
- scripts/run_docker_build.sh
We need `pelican 3.3` to create the system-test webpage env.
> Added pelican and its dependencies

- folium/meta.yaml
- Added Image Overlay. (andrewgiessel b625613)
- All popups can take a `popup_width` keyword to adjust the width in
text/HTML (ocefpaf #157).
- CAVEAT! Backwards incompatibly change: the keyword `width` in popups is now
`popup_width` to avoid confusion with map `width`.
> Updated folium to v0.1.6

- django-extensions/meta.yaml
1.5.7
-----
Changes:
- Fix: CreationDateTimeField, migration error
- Fix: ModificationDateTimeField, migration error
- Fix: shell_plus, options is not always in db config dictionary
- Fix: admin filters, contrib.admin.util fallback code
- Fix: graph_models, currectly support parsing lists for cli options
- Improvement: sqldsn, support postfix
- Improvement: utils, remove get_project_root function
1.5.6
-----
Changes:
- New: RandomCharField, prepopulates random character string
- New: (Not)NullFieldListFilter, filters for admin
- New: runserver_plus, integrate with django-pdb
- New: runserver_plus, add check_migrations from Django
- Improvement: show_urls, nested namespace support
- Improvement: show_urls, allow to specify alternative urlconf
- Improvement: show_urls, support i18n_patterns …
> Updated django-extensions to 1.5.7

- nn/build.sh
- nn/meta.yaml
**DO NOT MERGE THIS:**  I am waiting for an official release.  If that does not happen than we can consider merging it.
This PR fixes the license and source for the code.
NB: The `triangle.[c,h]` license is non-free for commercial use! :ghost:
> Fixed nn source and license

- testfixtures/meta.yaml
- Add wheel distribution to release.
- Attempt to fix up various niggles from the move to Travis CI for doing releases.
> Updated testfixtures to 4.3.3

- genshi/bld.bat
- genshi/build.sh
- genshi/meta.yaml
- httplib2/bld.bat
- httplib2/build.sh
- httplib2/meta.yaml
- pastescript/bld.bat
- pastescript/build.sh
- pastescript/meta.yaml
- pydap/bld.bat
- pydap/build.sh
- pydap/meta.yaml
- pyfvcom/bld.bat
- pyfvcom/build.sh
- pyfvcom/meta.yaml
- pyseidon/bld.bat
- pyseidon/build.sh
- pyseidon/meta.yaml
- pyseidon/setup.patch
This PR adds [PyFVCOM](https://github.com/pwcazenave/PyFVCOM) and [PySeidon](https://github.com/GrumpyNounours/PySeidon).  Both are not Python 3 ready.
`PySeidon` depends on `pydap` which needs `genshi`, `httplib2`, and `pastescript`.
> Added PyFVCOM and PySeidon

- .travis.yml
- appveyor.yml
- github3.py/meta.yaml
- pynco/meta.yaml
- scripts/run_docker_build.sh
- xray/meta.yaml
> Enable Python3.5

- pygridgen/meta.yaml
- pygridtools/meta.yaml
Until we fix `pygridgen` for Python 3.5 I am disabling the py3k builds.
> Disable pygridgen on Python 3

- appveyor.yml
Workaround conda's bad git log parsing.
(See https://github.com/conda/conda-build/issues/349#issuecomment-79450541.)
> Using Miniconda3 on Windows

- pygridgen/meta.yaml
- pygridtools/meta.yaml
Hey -- I made my employer the owner of the pygridtools library and upped the git tag to v0.2.
I also changed the dependencies of pygridgen  to skip basemap in favor of pyproj (should significantly reduce the build size and time).
> Pygridtools from Geosyntec, new version

- cartopy/meta.yaml
- proj4/bld.bat
- proj4/meta.yaml
For some reason that escapes me `cartopy` fails to build on Windows with `proj 4.9.2`. 
In this PR I re-add `proj 4.9.1` just to issue a new release (`5`).  I had a broken release somewhere and it is easier to re-build it then to find which one and delete the binary.
I also pin `numpy` to avoid picking up `1.10.0` due to `ValueError: numpy.dtype has the wrong size, try recompiling`.  I guess we will have to avoid a little bit to use `numpy 1.10.0`.
Note that I will return the `proj 4.9.2` in another PR.  Both OSX and Linux cartopy seemed OK with the newer version.
> Pin proj version

- pyresample/meta.yaml
- Bugfix: Accept unicode proj4 strings. Fixes #24. [Martin Raspaud]
- Add python-configobj as a rpm requirement in setup.cfg. [Martin
Raspaud]
- Add setup.cfg to allow rpm generation with bdist_rpm. [Martin Raspaud]
- Bugfix to address a numpy DeprecationWarning. [Martin Raspaud]
Numpy won't take non-integer indices soon, so make index an int.
> Updated pyresample to 1.1.4

- cartopy/meta.yaml
- cdo/build.sh
- cdo/meta.yaml
- proj.4/bld.bat
- proj.4/build.sh
- proj.4/meta.yaml
- proj4/bld.bat
The default channel uses the name `proj.4` instead of `proj4` (see https://github.com/ioos/conda-recipes/issues/413#issue-104850388).  That results in two versions of Proj.4 being installed depending on the package the users are trying to install.  I am renaming ours to reflect the same names found in the default channel in order to avoid that.
Note that we are using `proj.4 4.9.2` everywhere but cartopy on Windows.
> Rename proj4 to proj.4

- .travis.yml
Latest conda-build introduced a [bug](https://travis-ci.org/ioos/conda-recipes/builds/85940423#L2326) that I believe is already fixed [here](https://github.com/conda/conda-build/commit/b758f1b1ac0c3efbb4d5cc486ab54270595356b4), but we need to downgrade conda-build until Continuum issues a new release.
Ping @pelson in case you get hit by this.
> Downgrade conda build

- Dockerfile
We will need `cmake` on Linux in the near future (#523).
> Install cmake

- pycsw/build.sh
- pycsw/meta.yaml
The 1.10.3 release is a maintenance release, addressing the following fixes:
- enhance ISO 19119 link parsing for srv:serviceType
- centralize XML parser across codebase
> Updated pycsw to 1.10.3

- gridgen/meta.yaml
I guess we won't see releases, but the code is being updated.  Here is the changelog since the last version:
```
v. 1.51.2, 7 October 2015
-- A bit of clean-up in sc_z2w().
v. 1.51.1, 5 October 2015
-- Handled singularity in sc_prod() by adding test on absolute
value of the argument of clog().
v. 1.51.0, 2 October 2015
-- Added a new option: taking care of geographic coordinates. If there
is entry "geographic <lon0> <lat0>" in the parameter file then the
input coordinates are assumed to be geographic. They are internally
converted to stereographic projection with the South Pole at
(<lon0>, <lat0>) and converted back during the output of the grid
nodes.
v. 1.50, 25 September 2015
-- Minor changes to makefile.in: added $(LDFLAGS) for target
`libgridgen.so' (thanks to @ocefpaf for pointing), …
```
> Updated gridgen to 1.52.2

- django-debug-toolbar/meta.yaml
Change log
==========
1.4
---
This version is compatible with the upcoming Django 1.9 release. It requires
Django 1.7 or later.
New features
~~~~~~~~~~~~
* New panel method :meth:`debug_toolbar.panels.Panel.generate_stats` allows panels
to only record stats when the toolbar is going to be inserted into the
response.
Bugfixes
~~~~~~~~
* Response time for requests of projects with numerous media files has
been improved.
> Update django-debug-toolbar to 1.4

- setuptools_scm/meta.yaml
v1.8.0
======
* fix issue with setuptools wrong version warnings being printed to standard
out. User is informed now by distutils-warnings.
* restructure root finding, we now reliably ignore outer scm
and prefer PKG-INFO over scm, fixes #43 and #45
> Update setuptools_scm to 1.8.0

- pytest-django/meta.yaml
Changelog
=========
2.9.1
-----
Bug fixes
^^^^^^^^^
* Fix regression introduced in 2.9.0 that caused TestCase subclasses with
mixins to cause errors. Thanks MikeVL for `the bug report
<https://github.com/pytest-dev/pytest-django/issues/280>`_.
2.9.0
-----
2.9.0 focus on compatibility with Django 1.9 and master as well as pytest 2.8.1
and Python 3.5
Features
^^^^^^^^
* `--fail-on-template-vars` - fail tests for invalid variables in templates.
Thanks to Johannes Hoppe for idea and implementation. Thanks Daniel Hahler
for review and feedback.
Bug fixes
^^^^^^^^^
* Ensure urlconf is properly reset when using @pytest.mark.urls. Thanks to
Sarah Bird, David Szotten, Daniel Hahler and Yannick PÉROUX for patch and
discussions. Fixes `issue #183 …
> Update pytest-django to 2.9.1

- xray/meta.yaml
```
What's New
==========
v0.6.1 (21 October 2015)
This release contains a number of bug and compatibility fixes, as well
as enhancements to plotting, indexing and writing files to disk.
Note that the minimum required version of dask for use with xray is now
version 0.6.
API Changes
- The handling of colormaps and discrete color lists for 2D plots in
:py:meth:`~xray.DataArray.plot` was changed to provide more compatibility
with matplotlib's ``contour`` and ``contourf`` functions (:issue:`538`).
Now discrete lists of colors should be specified using ``colors`` keyword,
rather than ``cmap``.
Enhancements
- Faceted plotting through :py:class:`~xray.plot.FacetGrid` and the
:py:meth:`~xray.plot.plot` method. See :ref:`plotting.faceting` for more details
and examples.
- …
```
> Updated xray to 0.6.1

- netcdf4/build.sh
- netcdf4/meta.yaml
- netcdf4/run_test.py
This PR fixes two problems with the default channel netCDF4-python
- compiles it with cython so we can use the `.filepath()` method
- Updates to 1.2.1 (the default channel is stuck at `1.1.9`)
```
version 1.2.1 (tag v1.2.1rel)
=============================
* add the capability to slice variables with unsorted integer sequences,
or integer sequences with duplicates (issue #467). This was done
by converting boolean array slices to integer array slices internally,
instead of the other way around.
* raise TypeError if masked array assigned to a VLEN str variable slice
(issue #464).
* Ellipsis now can be used with scalar VLEN str variables (issue #458).
Slicing of scalar VLEN (non-str) variables now works.
* Allow non-positive reference years in non-real-world calendars
(issue #442).
version …
```
> Latest netCDF4-python compiled with Cython

- conda-execute/bld.bat
- conda-execute/build.sh
- conda-execute/meta.yaml
@pelson I wanted to avoid the duplication, but it seems that conda is forcing us in the wrong direction:
```shell
> anaconda copy conda-forge/conda-execute/0.4.0 --to-owner ioos
Using anaconda-server api site https://api.anaconda.org
[ServerError] Copying anaconda packages temporarily disabled.
This issue is being tracked here:
https://github.com/Anaconda-Server/docs.anaconda.org/issues/119 
```
At least it is "temporarily."
> Added conda-execute

- mocsy/meta.yaml
There is a compiler issue when building `mocsy` for Python 3  om Windows.
NB: `mocsy` does work with Python3 though.
```python
running build_ext
Traceback (most recent call last):
File "setup.py", line 59, in <module>
maintainer_email='ocefpaf@gmail.com',
File "C:\conda\envs\_build\lib\site-packages\numpy\distutils\core.py", line 169, in setup
return old_setup(**new_attr)
File "C:\conda\envs\_build\lib\distutils\core.py", line 148, in setup
dist.run_commands()
File "C:\conda\envs\_build\lib\distutils\dist.py", line 955, in run_commands
self.run_command(cmd)
File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
cmd_obj.run()
File "C:\conda\envs\_build\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
r = self.setuptools_run()
File …
```
> no mocsy on py3k

- iso8601/bld.bat
- iso8601/build.sh
- iso8601/meta.yaml
Changes 0.1.11
- Remove logging (thanks to Quentin Pradet in https://bitbucket.org/micktwomey/pyiso8601/pull-requests/6/remove-debug-logging/diff)
- Add support for , as separator for fractional part (thanks to ecksun in https://bitbucket.org/micktwomey/pyiso8601/pull-requests/5/add-support-for-as-separator-for/diff)
- Add Python 3.4 and 3.5 to tox test config.
- Add PyPy 3 to tox test config.
- Link to documentation at http://pyiso8601.readthedocs.org/
> Updated iso8601 to 0.1.11

- djangorestframework/meta.yaml
**Date**: [4th November 2015][3.3.1-milestone].
* Resolve parsing bug when accessing `request.POST` ([#3592][gh3592])
* Correctly deal with `to_field` referring to primary key. ([#3593][gh3593])
* Allow filter HTML to render when no `filter_class` is defined. ([#3560][gh3560])
* Fix admin rendering issues. ([#3564][gh3564], [#3556][gh3556])
* Fix issue with DecimalValidator. ([#3568][gh3568])
**Date**: [28th October 2015][3.3.0-milestone].
* HTML controls for filters. ([#3315][gh3315])
* Forms API. ([#3475][gh3475])
* AJAX browsable API. ([#3410][gh3410])
* Added JSONField. ([#3454][gh3454])
* Correctly map `to_field` when creating `ModelSerializer` relational fields. ([#3526][gh3526])
* Include keyword arguments when mapping `FilePathField` to a serializer field. ([#3536][gh3536])
* Map …
> Updated djangorestframework to 3.3.1

- django-extensions/meta.yaml
Changelog
=========
1.5.9
-----
Changes:
- Fix: wheel still had the old migrations directory in the package
1.5.8
-----
Changes:
- Fix: migrations, fix BadMigrationError with Django 1.8+
- Fix: reset_db, Django 1.8+ compatibility fix
- Fix: runserver_plus, fix signature of null_technical_500_response for Django 1.8+
- Fix: graph_models, use force_bytes instead of .decode('utf8')
- Improvement: print_settings, add format option to only print values
- Improvement: print_esttings, add format option for simple key = value text output
- Improvement: email_export, documentation updates
- Improvement: shell_plus, auto load conditional db expressions Case and When
> Updated django-extensions to 1.5.9

- numdifftools/meta.yaml
- pbr/bld.bat
- pbr/build.sh
- pbr/meta.yaml
- pyscaffold/bld.bat
- pyscaffold/build.sh
- pyscaffold/meta.yaml
=========
Changelog
=========
Created with gitcommand: git shortlog v0.9.12..v0.9.13
Version 0.9.13, October 30, 2015
---------------------------------
pbrod (21):
* Updated README.rst and CHANGES.rst.
* updated Limits.
* Made it possible to differentiate complex functions and allow zero'th order derivative.
* BUG: added missing derivative order, n to Gradient, Hessian, Jacobian.
* Made test more robust.
* Updated structure in setup according to pyscaffold version 2.4.2.
* Updated setup.cfg and deleted duplicate tests folder.
* removed unused code.
* Added appveyor.yml.
* Added required appveyor install scripts
* Fixed bug in appveyor.yml.
* added wheel to requirements.txt.
* updated appveyor.yml.
* Removed import matplotlib.
Justin Lecher (1):
* Fix min version for numpy.
kikocorreoso …
> Updated numdifftools 0.9.13

- geopy/meta.yaml
* ADDED: Photon geocoder. Contributed by mthh.
* ADDED: Bing supports structured query parameters. Contributed by
SemiNormal.
* CHANGED: Geocoders send a `User-Agent` header, which by default is
`geopy/1.11.0`. Configure it during geocoder initialization. Contributed
by sebastianneubauer.
* FIXED: Index out of range error with no results using Yandex. Contributed
by facciocose.
* FIXED: Nominatim was incorrectly sending `view_box` when not requested,
and formatting it incorrectly. Contributed by m0zes.
> update geopy to 1.11.0

- appveyor.yml
- geopy/meta.yaml
Some Windows packages are inconsistent in the default channel.  Since `pylint` is used only for testing I am just skipping it for now.
> Skip pylint on py35+win64

- folium/meta.yaml
- ulmo/meta.yaml
I used an unreleased tag before. This is the final `v0.1.6`.
- Added default options to tile_layer (ozak 1ad2336)
- Introduce free scale for geo_json (Nikolay Koldunov 21e2757)
- Added Image Overlay. (andrewgiessel b625613)
- All popups can take a `popup_width` keyword to adjust the width in
text/HTML (ocefpaf 157).
- CAVEAT! Backwards incompatibly change: the keyword `width` in popups is now
`popup_width` to avoid confusion with map `width`.
- Simpler HTML repr (ocefpaf a343106)
- WMS layer (Martin Journois 610b42d)
- Stamentoner URL (ocefpaf 7003dc5)
> Switch to release

- geopandas/meta.yaml
- paegan-transport/meta.yaml
- pyoos/meta.yaml
- xray/meta.yaml
Some missing dependency is preventing some build on Windows64+Python 3.5
See #588
> Skip Windows 64 + Python 3.5

- pyoos/bld.bat
- pyoos/build.sh
- pyoos/meta.yaml
Pyoos builds but is not Python 3 compat.
NB: I am building for the PR https://github.com/ioos/pyoos/pull/49 to avoid importing pyoos at build time.
> Skip Pyoos on Python 3

- environment.yml
We are almost at a point where virtually all packages are available in Python 3.  So maybe it is good to enforce Python 2.7 in the `environment.yml` file to avoid undesirable upgrades.
> Enforce Python 2.7

- esmf/build.sh
- esmf/meta.yaml
- esmpy/build.sh
- esmpy/meta.yaml
I tested the recipes using the ``continuumio/anaconda`` Docker image:
```sh
apt-get update
apt-get install git build-essential gfortran
conda build esmpy
```
Builds and ``ESMPy`` tests worked fine. I did not test on an external container. I went for very slim recipes. Let's see how it goes!
Of note: 
* ``ESMPy v7`` will be coming out soonish causing changes to the testing. We can test externally for example.
* It looks like conda folks are considering adding a ``--depth`` flag to ``git clone`` which would reduce the size of the ``ESMF`` repo: https://github.com/conda/conda/issues/1262.
Things to do before merge:
Watchers: @cdeluca, @rokuingh
> Add Linux recipes for ESMF and ESMPy

- sci-wms/meta.yaml
[Bug] 107: Fix lat/lon order on UGRID datasets
[Bug] 105: Allow empty width/height parameters in GetLegendGraphic requests
[Feature] 101: Ability to view sci-wms logs from the web client (login only)
[Feature] 106: Support the COLORBARONLY parameter in GetLegendGraphic
> Bump sci-wms metapackage

- sparqlwrapper/meta.yaml
SPARQLWrapper's changelog:
-------------------------
2015-11-19  1.7.5   - Removed pip dependency on setup (issue 69)
> Updated sparqlwrapper to 1.7.5

- requests-toolbelt/meta.yaml
```
History
=======
0.5.0 -- 2015-11-24
More information about this release can be found on the `milestone
<https://github.com/sigmavirus24/requests-toolbelt/issues?utf8=%E2%9C%93&q=is%3Aall+milestone%3A0.5+>`_
for 0.5.0.
New Features
- The ``tee`` submodule was added to ``requests_toolbelt.downloadutils``. It
allows you to iterate over the bytes of a response while also writing them
to a file. The ``tee.tee`` function, expects you to pass an open file
object, while ``tee.tee_to_file`` will use the provided file name to open
the file for you.
- Added a new parameter to ``requests_toolbelt.utils.user_agent`` that allows
the user to specify additional items.
- Added nested form-data helper,
``requests_toolbelt.utils.formdata.urlencode``.
- Added the …
```
> Updated requests_toolbelt to 0.5.0

- testfixtures/meta.yaml
```
Changes
=======
.. currentmodule:: testfixtures
4.5.1 (23 November 2015)
- Switch from :class:`cStringIO` to :class:`StringIO` in :class:`OutputCapture`
to better handle unicode being written to `stdout` or `stderr`.
Thanks to "tell-k" for the patch.
4.5.0 (13 November 2015)
- :class:`LogCapture`, :class:`OutputCapture` and :class:`TempDirectory` now
explicitly show what is expected versus actual when reporting differences.
Thanks to Daniel Fortunov for the pull request.
4.4.0 (1 November 2015)
-----------------------
- Add support for labelling the arguments passed to :func:`compare`.
- Allow ``expected`` and ``actual`` keyword parameters to be passed to
:func:`compare`.
- Fix ``TypeError: unorderable types`` when :func:`compare` …
```
> Updated testfixtures to 4.5.1

- numdifftools/meta.yaml
=========
Changelog
=========
Created with gitcommand: git shortlog v0.9.13..v0.9.14
Version 0.9.14, November 10, 2015
---------------------------------
pbrod (53):
* Updated documentation of setup.py
* Updated README.rst
* updated version
* Added more documentation
* Updated example
* Added .landscape.yml     updated .coveragerc, .travis.yml
* Added coverageall to README.rst.
* updated docs/index.rst
* Removed unused code and added tests/test_extrapolation.py
* updated tests
* Added more tests
* Readded c_abs c_atan2
* Removed dependence on wheel, numpydoc>=0.5 and sphinx_rtd_theme>=0.1.7 (only needed for building documentation)
* updated conda path in .travis.yml
* added omnia channel to .travis.yml
* Added conda_recipe files     Filtered out warnings in limits.py
> Updated numdifftools to 0.9.14

- folium/meta.yaml
There is a significant change in the API in folium `v0.2.0` and this PR is to help people port their code.
Those who find their workflow broken due to the update must pin their folium version to `v0.1.6`.
> Building development version of folium

- netcdf4/bld.bat
- netcdf4/meta.yaml
- wera2netcdf/meta.yaml
~~Just testing.~~
The default channel is outdated (version 1.1.9 is two releases behind) and not build with Cython (so no `filepath` method).
> Test netCDF4 build on Windows

- fortran-magic/meta.yaml
Changelog
=========
0.6 / 2015-12-02
----------------
- Decode text before printing
- Call f2py module instead of binary (numpy >=1.10 is mandatory)
- Check if f2py command failed
Thanks to `Juan Luis Cano Rodríguez`_ for this contribution
.. _Juan Luis Cano Rodriguez: https://github.com/Juanlu001
> Updated fortran-magic to 0.6.1

- testfixtures/meta.yaml
Changes
=======
4.7.0 (10 December 2015)
- Add the ability to pass ``raises=False`` to :func:`compare` to just get
and resulting message back rather than having an exception raised.
4.6.0 (3 December 2015)
- Fix a bug that mean symlinked directories would never show up when using
:meth:`TempDirectory.compare` and friends.
- Add the ``followlinks`` parameter to :meth:`TempDirectory.compare` to
indicate that symlinked or hard linked directories should be recursed into
when using ``recursive=True``.
> testfixtures 4.7.0

- pyscaffold/meta.yaml
=============
Release Notes
=============
Version 2.5, 2015-12-09
=======================
- Usage of ``test-requirements.txt`` instead of ``tests_require`` in
``setup.py``, issue 71
- Removed ``--with-numpydoc`` flag since this is now included by default with
``spinx.ext.napoleon`` in Sphinx 1.3 and above
- Added small template for unittest
- Fix for the example skeleton file when using namespace packages
- Fix typo in devpi:upload section, issue 82
- Include ``pbr`` and ``setuptools_scm`` in PyScaffold to avoid dependency
problems, issue 71 and 72
- Cool logo was designed by Eva Schmücker, issue 66
> pyscaffold 2.5

- django-extensions/meta.yaml
Changelog
=========
1.6.0
-----
Changes:
- Fix: Django 1.9 compatibility
- New: runserver_plus, add --startup-messages to control when to show them
- New: added support for Python 3.5
- Improvement: show_template_tags, renamed from show_templatetags for consistancy
- Removed: jquery library (after dropping support for Django 1.5)
> django-extensions to 1.6.0

- setuptools_scm/meta.yaml
v1.10.1
=======
* fix issue 73 - in hg pre commit merge, consider parent1 instead of failing
v1.10.0
=======
* add support for overriding the version number via the 
environment variable SETUPTOOLS_SCM_PRETEND_VERSION
* fix isssue 63 by adding the --match parameter to the git describe call
and prepare the possibility of passing more options to scm backends
* fix issue 70 and 71 by introducing the parse keyword
to specify custom scm parsing, its an expert feature,
use with caution
this change also introduces the setuptools_scm.parse_scm_fallback
entrypoint which can be used to register custom archive fallbacks
> Updated setuptools_scm to 1.10.1

- netcdf4/meta.yaml
That was a left-over from my local build.
> No mingwpy for netCDF4-python

- snuggs/bld.bat
- snuggs/build.sh
- snuggs/meta.yaml
- snuggs/run_test.py
`snuggs` is a `rasterio` dependency that is not available Windows version in the `anaconda` channel (although I see it in the `anaconda-remove` and `anaconda-old` !? and somehow the "default" channel picks one of those up.).
In this PR:
- re-introduce `snuggs` in the IOOS channel
- bump the build number to address https://github.com/ioos/conda-recipes/issues/649#issuecomment-165073374
- package it for all platforms including Windows in our channel to avoid confusion
PS: The default channel does the same for `rasterio`.  Not sure why...
> IOOS snuggs

- rasterio/bld.bat
- rasterio/build.sh
- rasterio/meta.yaml
- rasterio/run_test.py
The default channel stopped updating `rasterio` at `0.25`.  See https://github.com/ioos/conda-recipes/pull/651#issue-122487200  also.
> Re add rasterio

- environment.yml
- fiona/meta.yaml
- gdal/meta.yaml
- rasterio/meta.yaml
This PR should get OSX up to speed with Windows and Linux.
> Fiona, rasterio, and geopandas for OSX+gdal 1.11.3.

- requests-toolbelt/meta.yaml
More information about this release can be found on the [0.5.1 milestone](https://github.com/sigmavirus24/requests-toolbelt/milestones/0.5.1)
- Now papers over the differences in requests' ``super_len`` function from
versions prior to 2.9.0 and versions 2.9.0 and later.
> requests-toolbelt 0.5.1

- geopandas/meta.yaml
- geopy/meta.yaml
`geopandas` needs `geopy 1.10.0` and we did not have that for `PY35`.  I will revert `geopy` back to `1.11.0` after `geopandas` is uploaded.
> GeoPandas PY35 OSX

- yaml2ncml/meta.yaml
This version turns on or off the "display" attribute based on included or excluded variables instead of removing them in the NcML.
> Update yaml2ncml to 0.3.0

- .travis.yml
We are using a conda packaged `gsl` and there is no need for the `apt` section.
> Travis-CI cleanup

- sparqlwrapper/meta.yaml
```
2015-12-18  1.7.6   - Removed wrong response encoding (issue #70)
- Authorization header bug when using Python 3 (issue #71)
```
> sparqlwrapper 1.7.6

- rasterio/meta.yaml
```
Changes
=======
0.31.0 (2015-12-18)
- Warn when rasters have no georeferencing and when the default identity
transform will be applied by GDAL (524, 527).
- Build OS X wheels using numpy>=1.10.2 (529).
- When reading image windows in previous versions, given a window with
((row_start, row_stop), (col_start, col_stop)) if the stop index is greater
than the width/height the start index effectively shifts as well. This can
manifest itself in pixel misalignment if, e.g. you read block windows with
a bit of padding to avoid edge effects. Now the window offsets are determined
solely by row_start and col_start.(532, 533).
```
> rasterio 0.31.0

- fiona/meta.yaml
1.6.3 (2015-12-22)
- Daytime has been decreasing in the Northern Hemisphere, but is now
increasing again as it should.
- Non-UTF strings were being passed into OGR functions in some situations
and on Windows this would sometimes crash a Python process (303). Fiona
now raises errors derived from UnicodeError when field names or field
values can't be encoded.
> fiona 1.6.3

- pyoos/meta.yaml
Version 0.7.0 is a pre-release version of Pyoos containing improved features, bug fixes and code clean ups.
- Conda package now available at anaconda ioos channel (@ocefpaf)
- Added a named project-level logger (@kwilcox)
- Added flatten_element utilities convenience function to return record-style time series representation by variable standard name (@emiliom)
- Improvements to collectors and parsers:
- CO-OPS (added SML 1.0.1 Network Identifier XPath) (@lukecampbell)
- IoosSweSos (improved robustness of variable/attribute detection and code clean-up in describe sensor metadata; TimeSeries bug fix) (@lukecampbell, @kwilcox)
- HADS (improved parser handling of datetimes, values, and NaN flags; improved collector datetime filter) (@emiliom, @daf, @kwilcox)
- NERRS (added optional, …
> Fix some packaging issues with pyoos

- pyscaffold/meta.yaml
=============
Release Notes
=============
Version 2.5.2, 2016-01-02
=========================
- Fix ``is_git_installed``
Version 2.5.1, 2016-01-01
=========================
- Fix: Do some sanity checks first before gathering default options
- Updated setuptools_scm to version 1.10.0
> pyscaffold 2.5.2

- msinttypes/meta.yaml
- msinttypes/source.txt
Somehow our binaries got corrupted on anaconda.org.  (See https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.1739/job/w2ox0n0r1dj4ueye#L1927.)
> Re-added msinttypes

- oct2py/meta.yaml
Release History
---------------
3.4.0 (2016-01-09)
++++++++++++++++++
- Improved handling of Octave executable
> oct2py 3.4.0

- siphon/meta.yaml
Siphon 0.3.2 released Oct 30. https://github.com/Unidata/siphon/releases/tag/v0.3.2
> Update siphon meta.yaml to new version

- colander/meta.yaml
1.2 (2016-01-18)
================
Features
--------
- Add new exception `UnsupportedFields`. Used to pass to the caller a list
of extra fields detected in a cstruct during deserialize.
See https://github.com/Pylons/colander/pull/241
- Add ``drop`` functionality to ``Sequence`` type.
See https://github.com/Pylons/colander/pull/225
Bug Fixes
---------
- ``SchemaNode`` will no longer assume the first argument to the constructor
is the schema type. This allows it to properly fallback to using the
``schema_type`` class attribute on subclasses even when using the
imperative API to pass options to the constructor.
- Fix a bug in which ``MappingSchema``, ``SequenceSchema`` and
``TupleSchema`` would always treat the first arg as the schema type. This
meant that it would fail if passed only nodes …
> colander 1.2

- httpretty/meta.yaml
Improvements:
* Refactored `core.py` and increased its unit test coverage to 80%. HTTPretty is slightly more robust now.
Bug fixes:
* POST requests being called twice [#100](https://github.com/gabrielfalcao/HTTPretty/pull/100)
> httpretty 0.8.14

- metakernel/meta.yaml
Release History
0.12.0 (2016-01-17)
+++++++++++++++++++
- Fixes for process metakernel
> metakernel 0.12.2

- uncertainties/meta.yaml
Version 2.4.7.1: the printing and formatting of ±inf±… now works.
±inf±… can now be printed and formatted.
This is consistent with the fact that such numbers with uncertainty can be created with uncertainties.ufloat().
This makes it easier to handle calculation that work with floats despite involving infinities.
> uncertainties 2.4.7.1

- matlab_kernel/bld.bat
- matlab_kernel/build.sh
- matlab_kernel/meta.yaml
New 2-step install method.  Making the package from the wheels instead.
> matlab_kernel 0.8.0

- oct2py/meta.yaml
Release History
---------------
3.5.0 (2016-01-23)
++++++++++++++++++
- Disable --braindead Octave argument.
> oct2py 3.5.0

- requests-toolbelt/meta.yaml
```
History
=======
0.6.0 -- 2016-01-27
More information about this release can be found on the `0.6.0 milestone`_.
New Features
~~~~~~~~~~~~
- Add ``AppEngineAdapter`` to support developers using Google's AppEngine
platform with Requests.
- Add ``GuessProxyAuth`` class to support guessing between Basic and Digest
Authentication for proxies.
Fixed Bugs
~~~~~~~~~~
- Ensure that proxies use the correct TLS version when using the
``SSLAdapter``.
- Fix an ``AttributeError`` when using the ``HTTPProxyDigestAuth`` class.
Miscellaneous
~~~~~~~~~~~~~
- Drop testing support for Python 3.2. virtualenv and pip have stopped
supporting it meaning that it is harder to test for this with our CI
infrastructure. Moving forward we will make a best-effort attempt to
support 3.2 but will …
```
> requests-toolbelt 0.6.0

- ulmo/meta.yaml
Changelog
---------
**0.8.2 (released 2016-02-02)**
- added modules for getting LCRA hydromet and water quality data
- fixed waterml parser bug that was affecting USGS NWIS data when
parameter data collected using multiple methods exist (e.g. water level
measured with RADAR and pressure transducer) through use of optional 'method'
kwarg
- fixed ncdc.ghcn.get_stations() failing tests with pandas==0.17.0
> ulmo 0.8.2

- cyordereddict/meta.yaml
@shoyer not sure if you use the IOOS channel but pretty soon I will be moving `xray`\*, `dask`, `cyordereddict` and the rest of its dependencies to `conda-forge`.
\* To me it will always be `xray` :grin:
> cyordereddict 1.0.0

- testfixtures/build.sh
- testfixtures/meta.yaml
4.8.0 (2 February 2016)
-----------------------
- Introduce a new :class:`Replace` context manager and make :class:`Replacer`
callable. This gives more succinct and easy to read mocking code.
- Add :class:`ShouldWarn` and :class:`ShouldNotWarn` context managers.
> testfixtures 4.8.0

- xarray/build.sh
- xarray/meta.yaml
This is a bug fix release that includes two small, backwards compatible enhancements.
We recommend that all users upgrade.
- Numerical operations now return empty objects on no overlapping labels rather
than raising ``ValueError`` (:issue:`739`).
- :py:class:`~pd.Series` is now supported as valid input to the ``Dataset``
constructor (:issue:`740`).
- Restore checks for shape consistency between data and coordinates in the
DataArray constructor (:issue:`758`).
- Single dimension variables no longer transpose as part of a broader
``.transpose``. This  behavior was causing ``pandas.PeriodIndex`` dimensions
to lose their type (:issue:`749`)
- :py:class:`~xarray.Dataset` labels remain as their native type on ``.to_dataset``.
Previously they were coerced to strings (:issue:`745`)
- Fixed a bug …
> xarray 0.7.1

- simplejson/build.sh
- simplejson/meta.yaml
Version 3.8.2 released 2016-02-14
* Fix implicit cast compiler warning in _speedups.c
* simplejson is now available as wheels for OS X and Windows thanks to Travis-CI
and AppVeyor respectively! Many thanks to @aebrahim for getting this party
started.
https://github.com/simplejson/simplejson/pull/130
https://github.com/simplejson/simplejson/issues/122
Version 3.8.1 released 2015-10-27
* Fix issue with iterable_as_array and indent option
https://github.com/simplejson/simplejson/issues/128
* Fix typo in keyword argument name introduced in 3.8.0
https://github.com/simplejson/simplejson/pull/123
> simplejson 3.8.2

- cdo/meta.yaml
- nco/meta.yaml
I am not sure if this is the way to go.  Ping @daf and @bekozi who reported #723 and #700 respectively.
I tested using my docker image by uninstalling all the compiler and related system libraries and then built the packages with the default channel's `gcc`.  It worked locally, but I am not sure if it will work using our Docker image. (If not I am considering removing all the compiler from that image too and re-build everything using conda's gcc.)
> Fix libgomp

- eofs/build.sh
- eofs/meta.yaml
- Allow arbitrary mode selection when reconstructing a field from EOFs.
- Auxiliary coordinates are now preserved in the eofs.iris and eofs.multivariate.iris interfaces.
- Improved documentation, including the addition of a developer guide.
> eofs 1.0.0

- cdo/meta.yaml
- nco/meta.yaml
This finishes #769. (This is what I get for sending PRs from the airport :unamused:)
Update: Taking this opportunity to bump `nco` to `v4.5.5`:
```
NCO fully supports CDF5-format datasets,
ncremap continues to accrue useful features, 
and some corner case bugs were fixed.
```
> Fix libgomp part 2

- uncertainties/build.sh
- uncertainties/meta.yaml
- 2.4.8: Friendlier completions in Python shells, etc.: internal functions should not appear anymore (for the user modules: uncertainties, uncertainties.umath and uncertainties.unumpy). Parsing the shorthand notation (e.g. 3.1(2)) now works with infinite values (e.g. -inf(inf)); this mirrors the ability to print such numbers with uncertainty. The Particle Data Group rounding rule is applied in more cases (e.g. printing 724.2±26.2 now gives 724±26). The shorthand+LaTeX formatting of numbers with an infinite nominal value is fixed. uncertainties.unumpy.matrix now uses .std_devs instead of .std_devs(), for consistency with floats with uncertainty (automatic conversion of code added to uncertainties.1to2).
> uncertainties 2.4.8

- eofs/meta.yaml
Changelog
=========
Release notes:
- Added an xarray interface allowing use of `xarray.DataArray` objects with eofs.
- Fix bug in setting ddof in `eofs.tools.iris.covariance_map()`, previously it was always 1 regardless of the ddof keyword.
- Better Python 2 and 3 support without relying on 2to3.
> eofs v1.1.0

- testfixtures/meta.yaml
Changes
=======
4.9.1 (19 February 2016)
- Fix for use with PyPy, broken since 4.8.0.
Thanks to Nicola Iarocci for the pull request to fix.
4.9.0 (18 February 2016)
- Added the `suffix` parameter to :func:`compare` to allow failure messages
to include some additional context.
- Update package metadata to indicate Python 3.5 compatibility.
Thanks for Felix Yan for the metadata patch.
Thanks to Wim Glenn for the suffix patch.
> testfixtures 4.9.1

- pyresample/build.sh
- pyresample/meta.yaml
Changelog
=========
1.1.6
-------
- Fix 35 supporting scipy kdtree again. [Martin Raspaud]
A previous commit was looking for a 'data_pts' attribute in the kdtree
object, which is available in pykdtree, but not scipy.
- Merge pull request 32 from mitkin/master. [Martin Raspaud]
[tests] Skip deprecation warnings in test_gauss_multi_uncert
- Merge remote-tracking branch 'gh-pytroll/pre-master' [Mikhail Itkin]
- Put quotes around pip version specifiers to make things work. [Martin
Raspaud]
- Install the right matplotlib in travis. [Martin Raspaud]
The latest matplotlib (1.5) doesn't support python 2.6 and 3.3. This patch
chooses the right matplotlib version to install depending on the python
version at hand.
- Skip deprecation warnings. [Mikhail Itkin]
Catch the rest of the warnings. Check if …
> pyresample 1.1.6

- django-grappelli/build.sh
- django-grappelli/meta.yaml
2.8.1 (March 7th, 2016)
-----------------------
* First release of Grappelli which is compatible with Django 1.9.
> django-grappelli 2.8.1

- appveyor.yml
I disabled the rolling builds on AppVeyor as it brings more trouble than solutions. This PR should implement the "right" thing.
> Alternative to rollout builds

- recipes/mocsy/meta.yaml
This should fix `mocsy` builds on Windows.
> Remove gcc from windows build.

- .travis.yml
Conda build downgrade needs to be after `obvci_install_conda_build_tools.py` to avoid being upgraded.
> Conda build downgrade was before obvci_install_conda_build_tools.py

- recipes/libspatialite/meta.yaml
- recipes/libxml2/meta.yaml
Should fix the `gdal` failure on OS X.
> Pin versions

- recipes/iris/meta.yaml
- recipes/snuggs/meta.yaml
Iris does not build on OS X and Python 3.
> Skip iris on OS X and Python 3

- environment.yml
@rsignell-usgs I removed the `ioos` channel and tweaked it a little bit to get this env file to work.
I removed `utilities` and `rdflib` that do not exist in conda-forge. The former should disappear and the latter is just not packaged yet.  Then renaming issue was with `paegan-transport` refusing to install with the rest of the stack. I need to check what is the conflict as conda is not very helpful there. Meanwhile I just removed it.
> Fix env file for conda-forge
