cov-core/meta.yaml, optcomplete/meta.yaml, pytest-cov/meta.yaml, tappy/meta.yaml
With these small fixes we will be able to fully parse the metadata in the yaml file and use tools like Obvius-CI to build everything with one command.  For example
`obvci_conda_build_dir.py conda-recipes rsignell --channel main`
Will build all packages inside the directory conda-recipes and upload to rsignell channel.
=> Fixes empty tests and bad version strings.

mpld3/bld.bat, mpld3/build.sh, mpld3/meta.yaml
@rsignell-usgs we already have mplexport so here is the missing package.
=> Added mpld3.

csa/build.sh, csa/meta.yaml, gridgen/build.sh, gridgen/meta.yaml, gridutils/build.sh, gridutils/meta.yaml, nn/build.sh, nn/meta.yaml, pygridgen/build.sh, pygridgen/meta.yaml, pygridgen/test.py
@rsignell-usgs Just copied the recipes from phobson here.
=> Added pygridgen and its dependencies.

.travis.yml
This PR adapts the travis-ci yaml file to build at IOOS binstar account.  It supersedes #49.
@rsignell-usgs Please merge this one first so we can slowly follow the package upload to binstar.
=> IOOS channel

mplexporter/meta.yaml
This PR fixes another issue uncovered by travis.
BTW the successful packages are already being uploaded
https://binstar.org/ioos?filter=all
=> Using master branch.

biggus/bld.bat, biggus/meta.yaml, cartopy/bld.bat, cartopy/cartopy.win.patch, cartopy/meta.yaml, cdat-lite/meta.yaml, cfchecker/meta.yaml, cfchecker/patch.diff, compliance-checker/meta.yaml, ecmwf_grib/meta.yaml, expat/bld.bat, expat/meta.yaml, expat/stdint.h, geos/bld.bat, geos/cmake.win.patch, geos/meta.yaml, jasper/build.sh, jasper/meta.yaml, proj4/bld.bat, pyepsg/bld.bat, pyke/bld.bat, pyshp/bld.bat, python-dateutil/bld.bat, udunits2/meta.yaml
Copied all of scitools channel Windows+MacOS build machinery.
=> Scitools windows

appveyor.yml
@rsignell-usgs No build will take place until we sort  #64 out.
=> Added `appveyor.yml`.

sci-wms-deps/bld.bat, sci-wms-deps/build.sh, sci-wms-deps/meta.yaml
@rsignell-usgs the package was renamed from `sci-wms` to `sci-wms-deps` to be more honest with the user :stuck_out_tongue_winking_eye:
=> Fix `sci-wms-deps` windows build+rename package.

pycsw/meta.yaml
=> Bump build number.

README.md
Updates the badge link to IOOS repository
=> Pointing to IOOS repository.

.travis.yml
Do not merge.  Just checking if this is useful.
=> Added conda info command to debug.

00_env_requirements/ioos/linux32_req.txt, 00_env_requirements/ioos/linux64_req.txt, 00_env_requirements/ioos/windows64_req.txt, ctd/bld.bat, ctd/build.sh, ctd/meta.yaml, gsw/bld.bat, gsw/build.sh, gsw/meta.yaml, oceans/bld.bat, oceans/build.sh, oceans/meta.yaml, qrcode/bld.bat, qrcode/build.sh, qrcode/meta.yaml, utilities/bld.bat, utilities/build.sh, utilities/meta.yaml
@rsignell-usgs These packages are used in my SECOORA notebooks.  You do not have to add them if you think they will not be used by the rest of the community.  I am OK installing them via pip or another conda channel.
=> Added remaining package need for SECOORA.

utilities/meta.yaml
I tagged a release.  (Downloading from master is not good practice.)
=> Fix repository URL and downloading from tag.

cov-core/meta.yaml, pytest-cov/meta.yaml
Updated `pytest-cov` and its dependency `cov-core`.
=> Updated `pytest-cov` and `cov-core`.

utilities/meta.yaml
@rsignell-usgs this release adds the second workaround for Win64.  (Hopefully the last one!)
=> Updated utilities.

cf_units/bld.bat, cf_units/build.sh, cf_units/meta.yaml
=> Added cf_units

utilities/bld.bat, utilities/build.sh, utilities/meta.yaml
@rsignell-usgs I just added `requests` and `owslib` to the dependencies, in case someone tries to use this utilities without our cartopy.
=> Added cartopy's optional deps here.

pymatbridge/bld.bat, pymatbridge/build.sh, pymatbridge/meta.yaml
@rsignell-usgs I have only one notebook that calls matlab :grin:, but I believe this might be important for other cases.
=> Added pymatbridge.

.travis.yml, nco-bindings/build.sh, nco-bindings/meta.yaml, nco/build.sh, nco/meta.yaml, pyaxiom/bld.bat, pyaxiom/build.sh, pyaxiom/meta.yaml, pyncml/bld.bat, pyncml/build.sh, pyncml/meta.yaml
=> Adding pyaxiom.

xray/bld.bat, xray/build.sh, xray/meta.yaml
[Release notes]( https://github.com/xray/xray/releases/tag/v0.4.1):
The release contains bug fixes and several new features. All changes should be fully backwards compatible.
Highlights include:
- Documentation sections on Time series data and Combining multiple files.
- resample method for resampling to a new temporal resolution like pandas
- first and last methods on groupby objects
- swap_dims method for swapping dimensions
- Fixed a critical bug with the scipy netCDF backend
=> Adding xray.

pyncml/bld.bat, pyncml/build.sh, pyncml/meta.yaml
Once this gets merged I am submitting `pyaxiom` too.
=> Added pyncml.

iris/build.sh, iris/meta.yaml
@rsignell-usgs do not merge.  I am just testing what is going on with `pp_packing`.
=> Re-enabled pp.

affine/bld.bat, affine/build.sh, affine/meta.yaml
1.1.0 (2014-11-13)
- add loadsw/dumpsw world file utilities (#6).
- Travis-CI and Coveralls config and web hooks added (#10).
=> Updated affine to 1.1.0

vispy/bld.bat, vispy/build.sh, vispy/meta.yaml
This example works using latest master works.
http://stackoverflow.com/questions/28732937/how-to-export-vispy-result-as-png-image/28734180#28734180
=> Added vispy.

rtree/build.sh, rtree/meta.yaml
@rsignell-usgs I am bypassing the build in OSX.  That is just until we find a way to build the package.
PS: That change also allows me to keep both repositories (IOOS and pyoceans) in sync using the same files.
=> Updated rtree and pass OSX build.

gridgen/meta.yaml
See https://github.com/phobson/gridgen/issues/1
=> Pinned version tag.

scp/bld.bat, scp/build.sh, scp/meta.yaml
- Add changelog
- Finish up py3k and unicode support
- Unicode should work on OSX, Windows and Linux
- Some tests have been added
=> Updated scp

boost/build.sh, boost/meta.yaml
**DO NOT MERGE THIS ONE YET**  I need to check what changed to be sure we are not breaking anything.
=> Updated boost.

brewer2mpl/bld.bat, brewer2mpl/build.sh, brewer2mpl/meta.yaml
This is the last update for brewer2mpl.  Once the binaries land on binstar we should deprecate it in favor of palettable.  See:  https://pypi.python.org/pypi/brewer2mpl and https://pypi.python.org/pypi/palettable/
=> Updated brewer2mpl

palettable/bld.bat, palettable/build.sh, palettable/meta.yaml
Version 2.0
-----------
* Change name of library to Palettable
* Add Tableau palettes
* Additional Wes Anderson palettes
* Pre-make all palettes so they are available at import time
* Change naming scheme to <name>_<number of colors>
=> Added palettable (former brewer2mpl)

geojson/bld.bat, geojson/build.sh, geojson/meta.yaml
1.0.9 (2014-10-05)
- Fix bug where unicode/non-string properties with a 'type' key cause a crash
1.0.8 (2014-09-30)
- Fix bug where unicode keys don't get decoded properly
- Add coords and map_coords utilities
=> Updated geojson

geolinks/bld.bat, geolinks/build.sh, geolinks/meta.yaml
@rsignell-usgs this is not an updated!  The metadata seemed to be from another package (version, URL, etc).  Can you review if this is the right package?
=> Fixed geolinks

thredds_crawler/bld.bat, thredds_crawler/build.sh, thredds_crawler/meta.yaml
Standard bug fixes since 0.6
- Added Size queries
- Added logging (in lieu of prints)
- Better Error Handling
- ISO related parameters
=> Updated thredds_crawler

pyhum/meta.yaml, simplekml/bld.bat, simplekml/build.sh, simplekml/meta.yaml
Latest `pyhum` depends on `simplekml`
=> Updated pyhum and added simplekml (dependency).

pygdp/bld.bat, pygdp/build.sh, pygdp/meta.yaml
- Added a requirements specifically for running tests.
- Bug fix on _generateFeatureRequest function.
=> Updated pyGDP

geolinks/meta.yaml
Thanks @tomkralidis for the release!
=> Updated geolinks

cartopy/bld.bat, cartopy/build.sh, cartopy/meta.yaml
Also added the Shapely version constraint.
=> Minor fixes for OSX.

nco/meta.yaml
@rsignell-usgs safe to merge.  I just added a summary.
=> Added summary

.travis.yml, cf_units/bld.bat, cf_units/build.sh, cf_units/meta.yaml
@rsignell-usgs This PR implements the changes we discussed via e-mail.
Note that this will disable the Linux builds!  I will be updating the Linux binaries manually using @pelson's docker images until we get `circle-ci` working.
=> Using travis-ci to build OSX only

utide/bld.bat, utide/build.sh, utide/meta.yaml
UTide is highly experimental an the module is a moving target right now.  Use at your own risk!
=> Added UTide

.travis.yml, cartopy/meta.yaml, geos/meta.yaml, shapely/meta.yaml
=> Fixed channel URL

.travis.yml, cartopy/meta.yaml, geos/meta.yaml, proj4/meta.yaml, shapely/meta.yaml, snuggs/meta.yaml
Changes
=======
1.3.1 (2015-04-03)
- Revert to operator functions in op_map.
=> Updates snuggs to 1.3.1

.travis.yml, cartopy/meta.yaml, geos/meta.yaml, proj4/meta.yaml, pyhum/meta.yaml, shapely/meta.yaml
Latest pyhum release.  There is no changelog  and the commit messages are dates only... :unamused:
=> Updates pyhum to v1.2.3

cf_units/meta.yaml
@rsignell-usgs first stable release of cf_units.
=> Stable release of cf_units

oceans/bld.bat, oceans/build.sh, oceans/meta.yaml
=> Updated oceans

pyugrid/bld.bat, pyugrid/build.sh
Missed that `bld.bat` :flushed:
=> Added bld.bat for Windows pyugrid.

rasterio/meta.yaml
Changes
=======
0.23.0
--------
- Redesign CLI as dynamically loaded entry points (#346).
=> Latest rasterio release.

compliance-checker/bld.bat, compliance-checker/build.sh, compliance-checker/meta.yaml
- Support for Windows through cf_units
- CI Travis Fixes
- Better GliderDAC compliance tests
- Better skip control for QC variables, now relies on 'flag_meanings' attribute.
- Fixes recursion bug
- Fixes horizontal grid check bug
=> Latest compliance-checker.

pymatbridge/bld.bat, pymatbridge/build.sh, pymatbridge/meta.yaml
- This version improves the installation process, relative to 0.5.
=> Latest pymatbridge 0.5.2

compliance-checker/meta.yaml
=> Bug fix release

vincent/bld.bat, vincent/build.sh, vincent/meta.yaml
Just adding a folium optional dependency.   Some of my old notebooks still use this for plotting.
=> Adding vincent (folium opt dep).

pyhum/meta.yaml
=> Updated PyHum to 1.3.0

biggus/meta.yaml
- Fix to ndarray indexing on LinearMosaic
- Support for dtype promotion on elementwise operations
- Addition of __orthogonal_indexing__ protocol
- Addition of the astype array method and associated AsDataTypeArray object
- Improved str and repr representations of arrays
=> biggus 0.11.0

ioos_qartod/bld.bat, ioos_qartod/build.sh, ioos_qartod/meta.yaml, quantities/bld.bat, quantities/build.sh, quantities/meta.yaml
@lukecampbell Can I try to sell you `cf_units` instead of `quantities` here?
=> Added ioos_qartod

argh/bld.bat, argh/build.sh, argh/meta.yaml, dj-static/bld.bat, dj-static/build.sh, dj-static/meta.yaml, django-debug-toolbar/bld.bat, django-debug-toolbar/build.sh, django-debug-toolbar/meta.yaml, django-extensions/bld.bat, django-extensions/build.sh, django-extensions/meta.yaml, django-grappelli/bld.bat, django-grappelli/build.sh, django-grappelli/meta.yaml, django-typed-models/bld.bat, django-typed-models/build.sh, django-typed-models/meta.yaml, pathtools/bld.bat, pathtools/build.sh, pathtools/meta.yaml, sci-wms/meta.yaml, static3/bld.bat, static3/build.sh, static3/meta.yaml, watchdog/bld.bat, watchdog/build.sh, watchdog/meta.yaml
This PR adds the last missing sci-wms dependency listed in `requirements.txt`, `requirements-dev.txt`, and `requirements-prod.txt`.
@kwilcox let me know if there is anything else you need.  I would like to have all the dependencies on the IOOS channel to make it easier for future users.
=> Added django-extensions.

udunits2/bld.bat
Already removed the file, but the copy line remained and somehow AppVeyor never complained about it...
=> Removed line copying unistd.h

petulant-bear/bld.bat, petulant-bear/build.sh, petulant-bear/meta.yaml
- Better unicode support (in support of IOOS Catalog)
- Bug fixes
=> Updated petulant-bear to v0.1.3

owslib/build.sh, owslib/meta.yaml
The changelog file is not updated since 2013!
https://github.com/geopython/OWSLib/blob/master/CHANGES.txt
=> Updated owslib to 0.9.0

xray/meta.yaml
This minor release fixes a few bugs and an inconsistency with pandas. It also adds the pipe method, copied from pandas.
=> Updated xray to version 0.5.1

paegan/bld.bat, paegan/build.sh, paegan/meta.yaml
PyPI release.
(Not sure where it came from!  [GitHub](https://github.com/asascience-open/paegan) still says "1.1.1".)
=> Updated paegan to 1.1.2

flopy/meta.yaml
This version has Python 3 support
=> Update flopy meta.yaml

cdo/meta.yaml
Safe merge.  Just added some extra metadata.
=> Added cdo summary.

affine/meta.yaml
1.2.0 (2015-06-01)
- Enable pickling of Affine objects
- Sort out the mixed up shearing parameters
=> Updated affine to 1.2.0

geojson/bld.bat, geojson/build.sh, geojson/meta.yaml
Changes
=======
1.1.0 (2015-06-08)
- Stop outputting invalid GeoJSON value id=null on Features
- https://github.com/frewsxcv/python-geojson/pull/53
=> Updated geojson to 1.1.0

udunits2/bld.bat, udunits2/meta.yaml, udunits2/patchbinary.py
- Replaced use of deprecated atof() with strtod().
=> Updated udunits to 2.2.20

palettable/bld.bat, palettable/build.sh, palettable/meta.yaml
Version 2.1
-----------
* Add cubehelix palettes (thanks @jonathansick and @jradavenport!)
* Add two new Wes Anderson palettes
=> Updated palettable to 2.1.1

yaml2ncml/bld.bat, yaml2ncml/build.sh, yaml2ncml/meta.yaml
@rsignell-usgs I re-created the `v0.1.0` release to reflect the actual working version and added it as a conda package.
It should be "usable," but there is still a lot of work to make this a more general tool.
=> Added yaml2ncml

ckanapi/bld.bat, ckanapi/meta.yaml
Just some cleanups.  In theory the build should get slightly faster by not calling those dependencies twice.
=> Removed unnecessary build reqs.

django-autoslug/bld.bat, django-autoslug/build.sh, django-autoslug/meta.yaml, sci-wms/meta.yaml
Catching up with latest `sci-wms` requirements.
=> Updated sci-wms requirements.

betamax-matchers/bld.bat, betamax-matchers/build.sh, betamax-matchers/meta.yaml, betamax/bld.bat, betamax/build.sh, betamax/meta.yaml, descartes/bld.bat, descartes/build.sh, descartes/meta.yaml, geojsonio/bld.bat, geojsonio/build.sh, geojsonio/meta.yaml, geopandas/bld.bat, geopandas/build.sh, geopandas/meta.yaml, github3.py/bld.bat, github3.py/build.sh, github3.py/meta.yaml, requests-toolbelt/bld.bat, requests-toolbelt/build.sh, requests-toolbelt/meta.yaml, uritemplate.py/bld.bat, uritemplate.py/build.sh, uritemplate.py/meta.yaml
Adds:
- descartes
- geopandas
- geojsonio.py
and some its dependencies.
=> Geospatial

proj4/build.sh, proj4/meta.yaml
Forgot to do this in PR #299 (That is why I avoid self-merges!)
=> Bump build number

.travis.yml, appveyor.yml, paegan/meta.yaml
=> Update paegan to 1.1.3

pyugrid/bld.bat, pyugrid/build.sh, pyugrid/meta.yaml
=> Update pyugrid to 0.1.5

pyaxiom/meta.yaml
Fixes bug with newer versions of netcdf4-python
=> Bump pyaxiom to 0.0.13

pysgrid/bld.bat, pysgrid/build.sh, pysgrid/meta.yaml
=> Updates pysgrid to 0.1.0

pyncml/bld.bat, pyncml/build.sh, pyncml/meta.yaml
=> Updated pyncml to 0.0.8

pyaxiom/meta.yaml
=> Updated pyaxiom to 1.0.0

sci-wms/bld.bat, sci-wms/build.sh, sci-wms/meta.yaml
- Updates to rest API, vectorscale, and vectorstep options.
=> Update sci-wms metapackage to 1.1.0

xray/meta.yaml
No changelog for this release...
=> Updated xray to 0.5.2

oceans/meta.yaml
- Lazy imports.
- Several minor bug fixes.
=> Update oceans to 0.2.5

.travis.yml, appveyor.yml
Continuum products names are moving target now...
=> conda-server -> anaconda-client

README.md
Changed `Binstar.org` to `Anaconda.org`.
=> Updated README URLs

ioos_qartod/meta.yaml
- Basic QARTOD test implementations
=> Updated ioos_qartod to 0.0.2

pyugrid/meta.yaml
- ugrid_wx is now an entry point.
=> Updated pyugrid to 0.1.6

utide/meta.yaml
Catching up with master (no new release yet).
=> Updated UTide

pytest-django/bld.bat, pytest-django/build.sh, pytest-django/meta.yaml
=> Added pytest-django

utilities/meta.yaml
* Parse HTML station names-strings.
* Added `fetch_range()`, `show_qr()`,`get_nbviewer()`, `save_html()`,
`start_log()`, `apply_skill()`, and `filter_series()`.
* Added `TaylorDiagram` class.
=> Update utilities to 0.2.6

setproctitle/meta.yaml
- Fixed build on VC (issues 20, 33).
- Added MANIFEST.in to the source distribution to help with RPM building (issue 30).
=> Updated setproctitle to 1.1.9

mo_pack/meta.yaml
- Adds compression and decompression support for run-length encoding.
=> Updated mo_pack to 0.2.0

obvious-ci/meta.yaml
I was testing with an accidentally commit this into master!
=> Fix build number

folium/bld.bat, folium/build.sh, folium/meta.yaml
Version 0.1.5 was not released.  Next folium will be 0.2.0, but that one still has a long way to go...
=> Update folium to 0.1.5

tardis/bld.bat, tardis/meta.yaml
Version 0.1.0
* Fixed `get_surface()` that demand all the z points.
* Fixed `get_nearest_water()` to loop over all the points until actually finds
water.
* Added `get_nearest_series()` when finding wanter is not an issue. (Much faster
than `get_nearest_water()`.
=> Updated tardis to v0.1.0

utilities/meta.yaml
Version 0.3.0
* Added a new module for Quality Assurance and Quality Control `qaqc.py`:
`has_time_gaps()`, `is_monotonically_increasing()`, `is_flatline()`,
`is_spike()`, `threshold_series()`, `filter_spikes()`, and `tukey53H()`.
* Added `is_station()` for faster checks than`is_model()`.
* Several bug fixes (See https://github.com/ocefpaf/boston_light_swim/issues/5)
* Deprecate `sos_request()` in favor of `collector2table()` to get a list of
available stations in a `pyoos` `collector` object.
* Renamed `coops2df` to the more general `pyoos2df`
(downloads both Coops and NDBC).
=> Updated utilities to 0.3.0

testfixtures/bld.bat, testfixtures/build.sh, testfixtures/meta.yml
For https://github.com/NOAA-ORR-ERD/PyGnome support
=> Add testfixtures library

.travis.yml, appveyor.yml, cf_units/meta.yaml, compliance-checker/meta.yaml, ecmwf_grib/meta.yaml, github3.py/meta.yaml, iris/meta.yaml, oceans/meta.yaml, octant/meta.yaml, optcomplete/meta.yaml, paegan-transport/meta.yaml, petulant-bear/meta.yaml, pycsw/meta.yaml, pygdp/meta.yaml, pyhum/meta.yaml, suds/meta.yaml, tardis/meta.yaml, ulmo/meta.yaml, unit_conversion/meta.yaml, utilities/meta.yaml, wicken/meta.yaml
=> Python 3 builds

awesome-slugify/meta.yaml, awesome-slugify/utf8.patch
=> Testing UTF8 patch

sci-wms/meta.yaml
=> Update sci-wms to 1.1.1

proj4/bld.bat, proj4/meta.yaml
See https://github.com/ioos/conda-recipes/pull/396/files#r38259958
=> Fix regression in the package

shapely/geos_c.win.patch, shapely/meta.yaml, shapely/osx-geos.patch
1.5.11
- Replace packaging.version with distutils.version
1.5.10 (2015-??-??)
- Monkey patch affinity module by absolute reference (#299).
=> Updated Shapely to 1.5.11

cartopy/meta.yaml, cf_units/meta.yaml, compliance-checker/meta.yaml, ecmwf_grib/meta.yaml, iris/meta.yaml, octant/meta.yaml, optcomplete/meta.yaml, paegan-transport/meta.yaml, petulant-bear/meta.yaml, pycsw/meta.yaml, pygdp/meta.yaml, pyhum/meta.yaml, suds/meta.yaml, tardis/meta.yaml, ulmo/meta.yaml, unit_conversion/meta.yaml, utilities/meta.yaml, wicken/meta.yaml
Both `build` and `run` python version must be defined.
=> Fix Python <3 builds

proj4/meta.yaml
See https://github.com/ioos/conda-recipes/pull/401
=> Proj4 test

appveyor.yml, pyke/meta.yaml
=> Python 3 pyke

ecmwf_grib/build.sh, ecmwf_grib/meta.yaml, ecmwf_grib/py3k.patch
Python 3 patch for `ecmwf_grib`. (See https://github.com/SciTools/conda-recipes-scitools/pull/79.)
=> py3_ecmwf_grib

pygc/bld.bat, pygc/build.sh, pygc/meta.yaml
pygc is a great circle calculation package, a requirement for modflow2netcdf
=> adding pygc

modflow2netcdf/bld.bat, modflow2netcdf/build.sh, modflow2netcdf/meta.yaml
This package converts USGS modflow ground water model data to netcdf
=> adding modflow2netcdf

owslib/meta.yaml
=> bump owslib to 0.9.1

README.md
=> Added circle-ci badge

cf_units/meta.yaml, scripts/run_docker_build.sh
=> Updated cf_units to v0.1.1

pysgrid/meta.yaml
=> Updated pysgrid to v0.1.1

oct2py/meta.yaml
No changelog for this release :unamused:
=> Updated oct2py to 3.3.1

pysgrid/meta.yaml
Removed the extra `v` :flushed:
=> Fix version string

appveyor.yml, mplleaflet/meta.yaml
- Python 3 compatible
- And some more...
=> Updated mplleaflet to 0.0.4

owslib/meta.yaml
=> Update owslib to 0.9.2

pygridtools/meta.yaml
=> pygridtools use released version

unit_conversion/meta.yaml
Getting it from my branch until the PR is merged.
=> Python3 unit_conversion

rdflib/bld.bat, rdflib/build.sh, rdflib/meta.yaml
- Added a Networkx connector 471, 507
- Added a graph_tool connector 473
- Added a graphs method to the Dataset object 504, 495
- Batch commits for SPARQLUpdateStore 486
=> Update rdflib to 4.2.1

djangorestframework/meta.yaml
=> Updated djangorestframework to 3.2.4

csa/build.sh, csa/meta.yaml
This PR builds a shared lib and fixes:
- The license
- The source for the code
=> Fixed csa license and source, add shared lib

proj4/meta.yaml
https://github.com/OSGeo/proj.4/blob/master/ChangeLog
=> Updated proj4 to 4.9.2

libspatialindex/bld.bat, libspatialindex/meta.yaml, rtree/bld.bat, rtree/find_libray_nix.patch, rtree/find_libray_win32.patch, rtree/find_libray_win64.patch, rtree/meta.yaml
Not sure if this is going to work...
Closes #224 and #87
=> Rtree for Windows

seawater/meta.yaml
=> Updated seawater to 3.3.4

geojson/meta.yaml
Changes
=======
1.3.0 (2015-08-11)
- Add utility to generate geometries with random data
- https://github.com/frewsxcv/python-geojson/pull/60
=> Updated geojson to 1.3.0

regex/meta.yaml
=> Updated regex to 2015.09.23

isodate/meta.yaml
CHANGES
=======
0.5.4 (2015-08-06)
- Fix parsing of Periods (Fabien Bochu)
- Make Duration objects hashable (Geoffrey Fairchild)
- Add multiplication to duration (Reinoud Elhorst)
=> Updated isodate to 0.5.4

gsl/build.sh, gsl/meta.yaml, nco/meta.yaml, scripts/run_docker_build.sh
Added a recipe for gsl and rebuilt nco to use that package instead of the system wide lib.
Fixes #472
=> Added gsl and re-compile nco

.travis.yml, pygridgen/meta.yaml, pygridtools/meta.yaml
I removed some binaries with "bad" string (`nppy{27,34}`) now I have to rebuild them with latest conda.
=> Build Python 34

Dockerfile, circle.yml, ecmwf_grib/meta.yaml, scripts/run_docker_build.sh
This docker image is build from the Dockerfile in this repository.
=> New docker image

fortran-magic/bld.bat, fortran-magic/build.sh, fortran-magic/meta.yaml
This PR adds the Fortran notebook magic.
=> fortran-magic

beautifulsoup4/meta.yaml
=> Updated beautifulsoup4 to 4.4.1

README.md
Added the binder badge so users can test the binaries here in an online interactive session of Jupyter Notebooks.
=> Binder badge

cartopy/meta.yaml
For proj for other platforms :ghost:
=> Fix proj dependecy

proj4/bld.bat, proj4/meta.yaml
I removed this version to get a new build for Windows.  Now that the build is online I am restoring the latest Proj version.
=> Restore the latest proj version

uncertainties/bld.bat, uncertainties/build.sh, uncertainties/meta.yaml
See https://pypi.python.org/pypi/uncertainties
=> Add uncertainties

shapely/bld.bat, shapely/geos_c.win.patch, shapely/meta.yaml, shapely/osx-geos.patch
See https://github.com/SciTools/cartopy/issues/682#issuecomment-148489292
=> Revert to Shapely 1.5.12

geojson/meta.yaml
=> Update geojson to 1.3.1

django-autoslug/meta.yaml
=> Updated django-autoslug 1.9.3

matlab_kernel/bld.bat, matlab_kernel/build.sh, matlab_kernel/meta.yaml, metakernel/bld.bat, metakernel/build.sh, metakernel/meta.yaml
=> Added matlab_kernel

oct2py/meta.yaml
=> Updated oct2py 3.3.3

h5netcdf/meta.yaml
=> Updated h5netcdf to 0.2.2

pyaxiom/meta.yaml
=> Updated pyaxiom 1.0.8

regex/meta.yaml
=> Updated regex to 2015.10.05

proj.4/build.sh, proj.4/make_check.patch, proj.4/meta.yaml
Added @Qulogic's patch to get `make check` working on OSX.
=> Added OSX make check patch

appveyor.yml, scripts/run_docker_build.sh
Now that I know it works I am downgrading conda in `AppVeyor` and `Circle-CI` config too.
See #528
=> Downgrade conda build

thredds_crawler/meta.yaml
=> Bump thredds_crawler to 1.1.0 and use PyPI for source

compliance-checker/meta.yaml, iris/meta.yaml, numdifftools/meta.yaml, octant/meta.yaml, optcomplete/meta.yaml, pastescript/meta.yaml, petulant-bear/meta.yaml, pycsw/meta.yaml, pydap/meta.yaml, pyfvcom/meta.yaml, pygdp/meta.yaml, pyhum/meta.yaml, pyproj/meta.yaml, pyseidon/meta.yaml, pywafo/meta.yaml, tardis/meta.yaml, utilities/meta.yaml, wicken/meta.yaml
=> Manual build string

netcdf4/meta.yaml
=> nc4 build string

cf_units/meta.yaml
=> np string for cf_units

cf_units/meta.yaml
Reverts ioos/conda-recipes#545
=> Revert "np string for cf_units"

cartopy/bld.bat, cartopy/build.sh, cartopy/meta.yaml, iris/bld.bat, iris/build.sh, iris/meta.yaml
Same as https://github.com/SciTools/conda-recipes-scitools/pull/122
=> Smaller sdist

owslib/bld.bat, owslib/build.sh, owslib/meta.yaml, owslib/source.txt
=> scitools owslib

blinker/bld.bat, blinker/build.sh, cc-plugin-glider/bld.bat, cc-plugin-glider/build.sh, modflow2netcdf/bld.bat, modflow2netcdf/build.sh, oceans/bld.bat, oceans/build.sh, pelican/bld.bat, pelican/build.sh, pykdtree/build.sh, pyncml/bld.bat, pyncml/build.sh, pyresample/bld.bat, pyresample/build.sh
Ping @rhattersley who found my copy-and-paste mistake [here](https://github.com/SciTools/conda-recipes-scitools/pull/128#discussion_r44114147).  Thanks!
=> Remove duplicate install

compliance-checker/meta.yaml
Became a dep upstream on Jul 10th 2015
=> Add jinja2 to compliance-checker requirements

mocsy/bld.bat, mocsy/build.sh, mocsy/meta.yaml, scripts/run_docker_build.sh
Closes #550 
Ping @emiliom for testing.
=> Added mocsy

appveyor.yml, octant/bld.bat, octant/build.sh, octant/meta.yaml, octant/setuptools.patch
Testing the same `pydistutils.cfg` that worked for [mocsy](#563).
=> Win64 Fortran extension

regex/meta.yaml
=> Updated regex to 2015.11.08

octant/meta.yaml
Disable until I find a fix for https://github.com/ioos/conda-recipes/pull/565#issuecomment-154883772.
=> Disable octant win

netcdf-fortran/build.sh, netcdf-fortran/meta.yaml
@emiliom netcdf-fortran is one of the dependencies need by pyferret.
=> Step 0 for pyferret

environment.yml
Added:
- cc-plugin-glider
- compliance-checker
- xray
Pinned:
- gdal <2  # fiona issues
=> Updated env

appveyor.yml, conda-execute/meta.yaml
=> Fix conda execute dependency

appveyor.yml
AppVeyor was successful #578, but not once that got merged. It seems I do need to expand the sources after the merge.
=> Another try for #578

appveyor.yml, compliance-checker/meta.yaml
=> Pin cf_units

appveyor.yml
=> fix_appveyor

geopandas/meta.yaml, geopy/bld.bat, geopy/build.sh, geopy/meta.yaml
These were taken from the requirements I found in the master branch of the project.
=> Updated geopandas optional dependencies

numdifftools/meta.yaml, pbr/meta.yaml, pyscaffold/meta.yaml, scripts/run_docker_build.sh
=> Enable Python 3.5 on Linux

.travis.yml, geopandas/meta.yaml, pygridgen/meta.yaml, pygridtools/meta.yaml, rtree/run_test.py
Fro Python3.5+OSX I am skipping:
- `geopandas`:  unknown missing dependency.
- `pygridgen`: `AttributeError: 'Gridgen' object has no attribute '_libgridgen'`
- `pygridtools`: Needs `pygridgen`
=> Python 3.5 OSX

appveyor.yml
=> Python 3.5 Windows

pygridgen/meta.yaml, pygridtools/meta.yaml
=> Update pygridgen to 0.1.1

environment.yml
Adding `launcher` so that folks can use it from the ioos environment
=> Adding launcher

geopandas/meta.yaml, paegan-transport/meta.yaml, pyproj/meta.yaml, ulmo/meta.yaml, xray/meta.yaml
Only until https://github.com/jswhit/pyproj/pull/32 gets merged upstream.
=> Fix pyproj py35 windows build

luigi/build.sh, luigi/meta.yaml, python-daemon/build.sh, python-daemon/meta.yaml
=> Add luigi 2.0.0 and python-daemon 2.0.6

luigi/build.sh, luigi/meta.yaml, python-daemon/build.sh, python-daemon/meta.yaml
Minor tweaks.  No need for new builds.
=> single-version-externally-managed

sci-wms/meta.yaml
See https://github.com/sci-wms/sci-wms/issues/105#issuecomment-158222752
=> pin sci-wms matplotlib version

setuptools_scm/meta.yaml
v1.9.0
======
* Add :code:`relative_to` parameter to :code:`get_version` function;
fixes 44 per 45.
=> Updated setuptools_scm to 1.9.0

regex/meta.yaml
=> Updated regex to 2015.11.22

mplleaflet/meta.yaml
=> Updated mplleaflet to 0.0.5

spyre/bld.bat, spyre/build.sh, spyre/meta.yaml
Description: `Spyre makes it easy to build interactive web applications, and requires no knowledge of HTML, CSS, or Javascript.`
=> Added spyre

wera2netcdf/bld.bat, wera2netcdf/build.sh, wera2netcdf/meta.yaml
A utility to convert WERA total ASCII files into CF NetCDF files.
=> Add wera2netcdf

wera2netcdf/build.sh, wera2netcdf/meta.yaml
No need to bump build number.  Just minor tweaks to the recipe.
=> Minor tweaks

utilities/meta.yaml
Changelog
---------
Version 0.4.0
* Simpler `fes_date_filter()`.
* Update to latest pandas syntax.
* Fix `get_coops_metadata()` to comply with latest Coops SensorML changes.
=> Updated to v0.4.0

appveyor.yml
=> New appveyor token

folium/meta.yaml
Just until we get a new release...
=> Bump folium master build

flopy/meta.yaml
Update meta.yaml to use version 3.2.3
=> Updated flopy to 3.2.3

gdal/bld.bat, gdal/build.sh, gdal/clang.patch, gdal/meta.yaml, gdal/prepend-dll.patch
=> Testing some patches

python-ternary/bld.bat, python-ternary/build.sh, python-ternary/meta.yaml
See https://github.com/marcharper/python-ternary#gallery
=> Adding python-ternary

geopandas/meta.yaml
Fixes #623 
This PR is related to #628, #633, and #624.
=> Pin geopandas gdal (fiona)

eofs/bld.bat, eofs/build.sh, eofs/meta.yaml
See http://ajdawson.github.io/eofs/
=> Adding eofs

gdal/meta.yaml
See https://github.com/ioos/conda-recipes/issues/623#issuecomment-164251839
=> Proj4 to proj.4

keepalive/meta.yaml
=> keepalive 0.5

metakernel/meta.yaml
=> metakernel 0.11.7

django-extensions/meta.yaml
=> django-extensions 1.6.1

djangorestframework/meta.yaml
=> djangorestframework 3.3.2

compliance-checker/meta.yaml
=> Free cf_units dependency

cmocean/bld.bat, cmocean/build.sh, cmocean/meta.yaml
See http://matplotlib.org/cmocean/
=> Added cmocean

environment.yml
- Removed `basemap`.  It was dragging our geos down to 3.3.3 and breaking stuff.
- Added `cmocean`
- Pin `gdal` and `geos`
=> Updated environment file

environment.yml
Cannot do `gdal=1.11.3` because of OSX :unamused:
=> Fix environmentfile

.travis.yml, gdal/meta.yaml
GDAL's build logs are over the 4 MB Travis-CI log limit.  I am trying to suppress the logs to see if I can build this...
=> Testing log supress

.travis.yml, gdal/meta.yaml
=> PY 34 and NPY 19

.travis.yml
=> PY 34 and NPY 110

.travis.yml, gdal/meta.yaml
=> PY 35 and NPY 19

.travis.yml
=> PY 35 and NPY 110

quantities/meta.yaml, quantities/run_test.py
- fixes a unit test, use q.nansum method, not np.nansum func
=> quantities 0.11.0

geopy/meta.yaml
=> Restore geopy

.travis.yml, antlr/CharScanner.patch, antlr/build.sh, antlr/meta.yaml, nco/meta.yaml
If this works we will get `ncap2` on OSX.
=> Conda gsl+antlr (nco).

pyspharm/bld.bat, pyspharm/build.sh, pyspharm/meta.yaml
See https://github.com/jswhit/pyspharm
=> pyspharm 1.0.9

windspharm/bld.bat, windspharm/build.sh, windspharm/meta.yaml, windspharm/run_test.sh
See https://github.com/ajdawson/windspharm
=> Windspharm 1.3.2

nitime/bld.bat, nitime/build.sh, nitime/meta.yaml
See https://github.com/nipy/nitime
=> nitime 0.5

utilities/meta.yaml
Changelog
---------
Version 0.4.1
* Fix bug in simpler `fes_date_filter()` and re-introduced the `overlaps` and
`within` searches.
=> utilities 0.4.1

gridfill/bld.bat, gridfill/build.sh, gridfill/meta.yaml
See https://github.com/ajdawson/gridfill
=> gridfill v0.3.0

environment.yml
Renamed `proj4` to `proj.4` in the `environment.yml` file.
=> fix proj.4 in env file

metakernel/meta.yaml
=> metakernel 0.11.8

quantities/meta.yaml
=> quantities 0.11.1

pyaxiom/meta.yaml
=> Bump pyaxiom to 1.1.4 (fillvalue bug when creating files from dataframe)

pywavelets/bld.bat, pywavelets/build.sh, pywavelets/meta.yaml, pywavelets/run_test.py
See https://github.com/PyWavelets/pywt/releases/tag/v0.4.0
=> pywavelets 0.4.0

pyproj/bld.bat, pyproj/build.sh, pyproj/meta.yaml, pyproj/run_test.py, pyproj/source.txt
See https://github.com/conda-forge/staged-recipes/pull/41
=> Fetch pyproj from conda_forge

click-plugins/meta.yaml
Changelog
=========
1.0.3 - 2016-01-05
- Include tests in MANIFEST.in - See further discussion in 8
=> click-plugins 1.0.3

Dockerfile
=> Add mercurial do the Docker image.

oil_library/bld.bat, oil_library/build.sh, oil_library/meta.yaml, py_gnome/bld.bat, py_gnome/build.sh, py_gnome/meta.yaml
See https://github.com/NOAA-ORR-ERD/PyGnome/issues/12#issuecomment-170897658
=> Adding py_gnome and oil_library

post_gnome/bld.bat, post_gnome/build.sh, post_gnome/meta.yaml, post_gnome/should_just_send_a_pr.patch
Adding post_gnome.
Ping @rsignell-usgs.  Not sure if the package will work.  I had to patch a few things just to get it to build.
=> post_gnome

pyhum/build.sh, pyhum/meta.yaml
=> pyhum 1.3.4

regex/build.sh, regex/meta.yaml
=> regex 2016.01.10

matlab_kernel/meta.yaml
=> matlab_kernel 0.6.10

django-grappelli/meta.yaml
Changelog
=========
2.7.4 (not yet released)
????????
=> django-grappelli 2.7.3

pyscaffold/meta.yaml
=> pyscaffold 2.5.3

Dockerfile
See https://github.com/conda/conda-build/pull/731
=> Workaround uncompress /gunzip

xarray/meta.yaml
Last missing optional dependency
=> Add dep pynio

xarray/meta.yaml
Why do I always forget about Windows? :unamused:
=> No pynio on Windows

freezegun/meta.yaml
0.3.6
-----
* Catch TypeError when fetching attribute values
* Speed improvements
* Add manual tick increment
=> freezegun 0.3.6

qrcode/bld.bat, qrcode/build.sh, qrcode/meta.yaml
Change log
==========
Version 5.2
===========
* Add ``--error-correction`` option to qr script.
* Fix script piping to stdout in Python 3 and reading non-UTF-8 characters in
Python 3.
* Fix script piping in Windows.
* Add some useful behind-the-curtain methods for tinkerers.
* Fix terminal output when using Python 2.6
* Fix terminal output to display correctly on MS command line.
Version 5.5.1
-------------
* Small fix to terminal output in Python 3 (and fix tests)
Version 5.5.2
-------------
* Revert some terminal changes from 5.2 that broke Python 3's real life tty
code generation and introduce a better way from Jacob Welsh.
=> qrcode 5.2.2

scripts/run_docker_build.sh
Or until we move to conda-build-all :wink:
=> Work around until new obvious-ci release

scripts/run_docker_build.sh
See https://github.com/ioos/conda-recipes/pull/735#issuecomment-176680341
=> Get latest obvious-ci release

.travis.yml, appveyor.yml, geojson/meta.yaml, scripts/run_docker_build.sh
Changes
=======
1.3.2 (2016-01-28)
- Add __version__ and __version_info__ attributes
- https://github.com/frewsxcv/python-geojson/pull/74
=> geojson 1.3.2

petulant-bear/meta.yaml
Placeholder while we wait for an official release.
=> petulant-bear 0.1.4.dev

petulant-bear/meta.yaml, wicken/build.sh, wicken/meta.yaml
- Python 2/3 codebase
Ping @daf.
=> Wicken v0.2.0 and petulantbear v0.2.0

esmf/build.sh, esmf/meta.yaml, esmpy/build.sh, esmpy/meta.yaml
=> ESMF 7.0.0

thredds_crawler/meta.yaml
Add the ability to filter by modified times
=> thredds_crawler 1.2.0

cyordereddict/build.sh, cyordereddict/meta.yaml
=> updated metadata

pyaxiom/build.sh, pyaxiom/meta.yaml
=> pyaxiom 1.1.7

pyproj/source.txt
Note to self.  In the future we might just copy the binary.
=> Fetch from conda-forge feedstock

metakernel/build.sh, metakernel/meta.yaml
=> metakernel 12.3

livereload/bld.bat, livereload/meta.yaml, mkdocs-bootstrap/bld.bat, mkdocs-bootstrap/meta.yaml, mkdocs-bootswatch/bld.bat, mkdocs-bootswatch/meta.yaml, mkdocs/bld.bat, mkdocs/meta.yaml
Use to build the `gh-pages` documentation.
=> Mkdocs and dependencies

folium/build.sh, folium/meta.yaml
Major changes to the API with the new plugin system,
and several new features in this version. For more information check the docs:
http://python-visualization.github.io/folium/
- Added control_scale (BibMartin and jelmelk 355)
- WMS styles (ocefpaf 348)
- Docs! (BibMartin 344, 337, 329)
- No tile option (ocefpaf 330)
- GeoJSON and TopoJSON `style_function` (BibMartin 317 and 266)
- Colormaps (BibMartin 300)
- Map CRS (BibMartin 297)
- GeoPandas drawing (BibMartin 296)
- Div Icons (BibMartin 250)
- CustomIcon (BibMartin 230)
- HeatMap (BibMartin 213)
And many bug fixes!
(See https://github.com/python-visualization/folium/issues?&q=milestone:v0.2.0+is:closed+label:bug)
=> Use the release

pyscaffold/build.sh, pyscaffold/meta.yaml
Version 2.5.4, 2016-02-10
=========================
- Fix problem with ``fibonacci`` terminal example
- Update setuptools_scm to v1.10.1
=> pyscaffold 2.5.4

wera2netcdf/meta.yaml
* Support for empty ASCII files
* Support for a dynamic number of reporting stations
=> Bump wera2netcdf to 0.0.3

luigi/build.sh, luigi/meta.yaml, python-daemon/build.sh, python-daemon/meta.yaml
=> luigi 2.0.1 and python-daemon 2.1.1

netcdf4/source.txt
Should fix the failures in our CIs.
=> Point to the feedstock.

codar2netcdf/bld.bat, codar2netcdf/build.sh, codar2netcdf/meta.yaml
A utility to convert CODAR total ASCII files into CF NetCDF files
=> Add codar2netcdf

codar2netcdf/build.sh, codar2netcdf/meta.yaml
Preparing the recipe to go to conda-forge.
=> Clean codar2netcdf recipe

gdal/meta.yaml
Should fix #771
(Ping @bekozi and thanks @mattexx for figuring this out.)
=> Added krb5 dependency

oct2py/build.sh, oct2py/meta.yaml
=> oct2py 3.5.1

windspharm/build.sh, windspharm/meta.yaml
=> windspharm 1.4.0

github3.py/build.sh, github3.py/meta.yaml
=> github3.py 1.0.0a4

wera2netcdf/build.sh, wera2netcdf/meta.yaml
=> wera2netcdf 0.0.4

descartes/build.sh, descartes/meta.yaml
Changes
=======
1.0.2 (2016-01-19)
- Slice coordinates to eliminate Z values of 3D geometries (PR 1).
=> descartes 1.0.2

pyscaffold/meta.yaml
Version 2.5.5, 2016-02-26
=========================
- Updated pbr to master at 2016-01-20
- Fix sdist installation bug when no git is installed, issue 90
=> pyscaffold 2.5.5

regex/build.sh, regex/meta.yaml
=> regex 2016.03.02

pyaxiom/meta.yaml
=> pyaxiom 1.1.8

pyhum/build.sh, pyhum/meta.yaml
=> pyhum 1.3.9

compliance-checker/meta.yaml
=> Update compliance-checker to 2.1.0

nco/meta.yaml
=> Fix nco #776

cdo/meta.yaml, libuuid/build.sh, libuuid/meta.yaml
Ping @DamienIrving.  Can you test this once the binaries land on the channel?
=> Fix cdo #776

pygeogrids/bld.bat, pygeogrids/meta.yaml, pyscaffold/meta.yaml
See https://github.com/TUW-GEO/pygeogrids
Ping @rsignell-usgs and @ChrisBarker-NOAA this package is for Regular grids what `pysgrid` and `pyugrid` are (should be?) for SGRID and UGRID.
=> pygeogrids

pykdtree/meta.yaml
=> pykdtree 1.1.1

cell_tree2d/bld.bat, cell_tree2d/meta.yaml
=> Adding cell_tree2d (pyugrid)

cdo/meta.yaml
=> Bump cdo build number

xarray/meta.yaml
What's New
==========
import numpy as np
import pandas as pd
import xray
import xarray
import xarray as xr
np.random.seed(123456)
v0.7.2 (13 March 2016)
----------------------
This release includes two new, entirely backwards compatible features and
several bug fixes.
Enhancements
~~~~~~~~~~~~
- New DataArray method :py:meth:`DataArray.dot` for calculating the dot
product of two DataArrays along shared dimensions. By
`Dean Pospisil <https://github.com/deanpospisil>`_.
- Rolling window operations on DataArray objects are now supported via a new
:py:meth:`DataArray.rolling` method. For example:
.. ipython::
:verbatim:
In [1]: import xarray as xr; import numpy as np
In [2]: arr = xr.DataArray(np.arange(0, 7.5, 0.5).reshape(3, 5),
dims=('x', 'y'))
In [3]: arr
Out[3]:
<xarray.DataArray (x: 3, …
=> xarray 0.7.2

pygeoif/bld.bat, pygeoif/build.sh, pygeoif/meta.yaml
Small style corrections to #807
=> Clean pygeoif

README.md
=> Update README with a conda-forge note

Dockerfile
Forgot that I use `wget` to download miniconda.
=> Re-add wget

recipes/geopandas/bld.bat, recipes/geopandas/meta.yaml
Ping @emiliom. The `conda-forge` version must be the latest release but we can relax that rule here. Let me know if that works for you.
=> Latest geopandas

recipes/cartopy/bld.bat, recipes/cartopy/build.sh, recipes/cartopy/meta.yaml, recipes/proj.4/meta.yaml
Use features to build `Proj.4` on Windows and update cartopy.
=> Fix Windows Proj.4

recipes/utilities/bld.bat, recipes/utilities/build.sh, recipes/utilities/meta.yaml
=> Update utilities to 0.5.0

recipes/iris/build.sh, recipes/iris/meta.yaml, recipes/iris/no_compile_setup.patch, recipes/tardis/meta.yaml, recipes/utilities/meta.yaml
=> Fix utilities build

environment.yml
@rsignell-usgs now we have `thredds_crawler` here too :smile:
=> Add thredds_crawler

Dockerfile
Some people are still using the Dockerimage and need this update.
=> Drop obvious-ci
